var MSG = {
  title: "Código",
  blocks: "Bloques",
  editor: "Lua",
  board: "Placa",
  console: "Consola",	
  status: "Estado",
  fileSystem: "Archivos",
  linkTooltip: "Guarda conexión a los bloques.",
  runTooltip: "Ejecuta el programa",
  badCode: "Error de programa:\n%1",
  timeout: "Se excedio el máximo de iteraciones ejecutadas permitidas.",
  trashTooltip: "Descartar todos los bloques.",
  catIO: "Entrada / Salida",
  catControl: "Control",
  catExceptions: "Excepciones",
  catThreads: "Hilos",
  catLogic: "Lógica",
  catLoops: "Secuencias",
  catMath: "Matemáticas",
  catText: "Texto",
  catLists: "Listas",
  catColour: "Color",
  catVariables: "Variables",
  catFunctions: "Funciones",
  listVariable: "lista",
  textVariable: "texto",
  httpRequestError: "Hubo un problema con la petición.",
  linkAlert: "Comparte tus bloques con este enlace:\n\n%1",
  hashError: "«%1» no corresponde con ningún programa guardado.",
  xmlError: "No se pudo cargar el archivo guardado.  ¿Quizá fue creado con otra versión de Blockly?",
  badXml: "Error de análisis XML:\n%1\n\nSelecciona OK para abandonar tus cambios o Cancelar para seguir editando el XML.",
  boardConnected: "Placa conectada",
  boardDisconnected: "Placa desconectada",
  information: "Información",
  sendingCode: "Enviando código ...",
  retrievingDirectory: "Obteniendo directorio ...",
  downloadingFile: "Descargando archivo",
  sendingFile: "Enviando archivo",
  DELETE_EDIT_CODE: "¿Quieres borrar el código que estas editando actualmente?",
  catIODigital: 'Digital',
  catIOAnalog: 'Analógico',
  catIOPwm: 'PWM',
  boardInBootloaderMode: 'Tu placa está se está reiniciando y aún no tiene un firmware. ¿Deseas instalar el firmware ahora?',
  firmwareUpgraded: 'Firmware actualizado',
  installNow: 'Si, instala ahora',
  notNow: 'Ahora no',	
  downloadingFirmware: 'Descargando el firmware',
  rebooting: 'Reiniciando ...',
  newFirmware: 'Una nueva versión del firmware está disponible para tu placa. ¿Deseas actualizar?.',
  firmwareNoNewVersion: 'No hay una nueva versión disponible. Tu placa está actualizada.',
  warning: "Atención",
  switchToBlocksWarning: "El código de Lua se ha modificado. Actualmente la función de sincronización entre Lua y bloques no está implementada. Se perderán todos los cambios en el código Lua. ¿Quieres continuar?.",
  yes: 'Si',
  no: 'No', 
  waitingForBoard: 'Conecta una placa ...',
  target: 'Destino: ',
  loadBlockTitle: 'Selecciona un archivo para cargar ...',
  loadFromDesktop: 'Cargar desde el ordenador ...',
  saveBlockTitle: 'Selecciona un archivo o carpeta donde guardar ...',
  saveToBoard: 'Guardar en la placa',
  saveToDesktop: 'Guardar en el ordenador ...',
  saveAs: 'Guardar como: ',
  run: 'Ejecutar',
  catComm: "Comunicaciones",
  catI2C: "I2C",
  runtimeError: "Error en tiempo de ejecución",
  ok: "Deacuerdo",
  youHaveAnError: "Tienes un error en tu código:",
  value: 'valor',
  catLora: "LoRa",
  catLoraOTAA: "OTAA",
  catLoraABP: "ABP",
  catDelays: "Retardos",
  catEvents: "Eventos",
  item: "Elemento",
  value: "Valor",
  installedFirmware: "Firmware instalado",
  cpuModel: "Modelo de CPU",
  checkForFirmwareUpdates: "Comprobar si hay actualitzaciones de firmware ..."
};
