var MSG = {
  title: "Código",
  blocks: "Bloques",
  linkTooltip: "Guarda conexión a los bloques.",
  runTooltip: "Ejecute el programa definido por los bloques en el área de trabajo.",
  badCode: "Error del programa:\n%1",
  timeout: "Se excedio el máximo de iteraciones ejecutadas permitidas.",
  trashTooltip: "Descartar todos los bloques.",
  catLogic: "Lógica",
  catLoops: "Secuencias",
  catMath: "Matemáticas",
  catText: "Texto",
  catLists: "Listas",
  catColour: "Color",
  catVariables: "Variables",
  catFunctions: "Funciones",
  listVariable: "lista",
  textVariable: "texto",
  httpRequestError: "Hubo un problema con la petición.",
  linkAlert: "Comparte tus bloques con este enlace:\n\n%1",
  hashError: "«%1» no corresponde con ningún programa guardado.",
  xmlError: "No se pudo cargar el archivo guardado.  ¿Quizá fue creado con otra versión de Blockly?",
  badXml: "Error de análisis XML:\n%1\n\nSelecciona OK para abandonar tus cambios o Cancelar para seguir editando el XML.",
	
  // WHITECAT	
  editor: "Lua",
  board: "Placa",
  console: "Consola",	
  status: "Estado",
  catIO: "Entrada / Salida",
  fileSystem: "Archivos",
  catControl: "Control",
  catExceptions: "Excepciones",
  catThreads: "Hilos",
  boardConnected: "Placa conectada",
  boardDisconnected: "Placa desconectada",
  information: "Información",
  sendingCode: "Enviando código ...",
  retrievingDirectory: "Obteniendo directorio ...",
  downloadingFile: "Descargando archivo",
  sendingFile: "Enviando archivo",
  DELETE_EDIT_CODE: "¿Quieres borrar el código que estas editando actualmente?",
  catIODigital: 'Digital',
  catIOAnalog: 'Analógico',
  catIOPwm: 'PWM',
  boardInBootloaderMode: 'Tu placa está se está reiniciando y aún no tiene un firmware. ¿Deseas instalar el firmware ahora?',
  firmwareUpgraded: 'Firmware actualizado',
  installNow: 'Si, instala ahora',
  notNow: 'Ahora no',	
  downloadingFirmware: 'Descargando el firmware',
  rebooting: 'Reiniciando ...',
  newFirmware: 'Una nueva versión del firmware está disponible para tu placa. ¿Deseas actualizar?.',
  firmwareNoNewVersion: 'No hay una nueva versión disponible. Tu placa está actualizada.',
  warning: "Atención",
  switchToCodeWarning: "Vas a cambiar de modelo de programación. Tu espacio de trabajo en bloques será borrado. Podrás recuperarlo después, si decides volver a bloqles. ¿Continuar?.",
  switchToBlocksWarning: "Vas a cambiar de modelo de programación. Tu código Lua será borrado. Podrás recuperarlo después, si decides volver a Lua. ¿Continuar?.",
  yes: 'Si',
  no: 'No', 
  waitingForBoard: 'Conecta una placa ...',
  target: 'Destino: ',
  loadBlockTitle: 'Selecciona un archivo para cargar ...',
  loadFromDesktop: 'Cargar desde el ordenador ...',
  saveBlockTitle: 'Selecciona un archivo o carpeta donde guardar ...',
  saveToBoard: 'Guardar en la placa',
  save: 'Guardar',
  saveToDesktop: 'Guardar en el ordenador ...',
  saveAs: 'Guardar como: ',
  run: 'Ejecutar',
  catComm: "Comunicaciones",
  catI2C: "I2C",
  runtimeError: "Error en tiempo de ejecución",
  ok: "Deacuerdo",
  youHaveAnError: "Tienes un error en tu código:",
  value: 'valor',
  catLora: "LoRa",
  catLoraOTAA: "OTAA",
  catLoraABP: "ABP",
  catDelays: "Retardos",
  catEvents: "Eventos",
  item: "Elemento",
  value: "Valor",
  installedFirmware: "Firmware instalado",
  cpuModel: "Modelo de CPU",
  checkForFirmwareUpdates: "Comprobar si hay actualitzaciones de firmware ...",
  switchToBlocksTooltip: 'Cambia a bloques',
  switchToCodeTooltip: 'Cambia a Lua',
  loadButtonTooltip: 'Carga un programa',
  saveButtonTooltip: 'Guarda el programa', 
  saveAsButtonTooltip: 'Guarda el programa como ...',
  rebootButtonTooltip: 'Reinicia la placa',
  stopButtonTooltip: 'Para el programa',
  cancel: 'Cancelar',
  error: 'Error',
  youHaveAnErrorInSettings: 'Tienes un error en el archivo settings.json:',
  youHaveAnErrorInFile: 'Tienes un error en el archivo ',
  missingAdapterId: 'No se encuentra el id del adaptador',
  missingAdapterPlatform: "No se encuentra la informacíon para la plataforma ",
  missingAdapterPath: "No se encuentra la propiedad path para la plataforma ",
  missingAdapterDisplayName: "No se encuentra la propiedad displayName para la plataforma ",
  missingBoardId: 'No se encuentra el id de la placa',
  catSensor: "Sensores",
  catOperators: "Operadores",
  catOperatorsNumeric: "Númericos",
  catOperatorsLogic: "Lógicos",
  catOperatorsText: "Texto",
  catActuators: "Actuadores",
  catServo: "Servo",
  catTFT: "Display TFT",
  catWIFI: "Wi-Fi",
  catNET: "Red",
  catMQTT: "MQTT",
  attachBoardForUseThisOption: "Por favor, conecta una placa antes de utilizar esta opción.",
  alert: "Atención",
  pleaseUpgradeAgent: "Hay una nueva versión de The Whitecat Create Agent. Por favor, actualiza a la nueva versión. <br><br><button type=\"button\" class=\"btn btn-success btn-alert-instructions\" data-url=\"https://whitecatboard.org/git/wiki/whitecat-create-agent/How-to-update\">Abrir las instrucciones para actualizar ...</button>",
  thisFuntionRequiresUpdateAgent: "Esta función requiere una nueva versión de The Whitecat Create Agent. <br><br><button type=\"button\" class=\"btn btn-success btn-alert-instructions\" data-url=\"https://whitecatboard.org/git/wiki/whitecat-create-agent/How-to-update\">Abrir las instrucciones para actualizar ...</button>",
  connectABoard: "Conecta una placa",
  downloadingPrerequisites: "Descargando prerrequisitos",
  uploadingFramework: "Subiendo prerrequisitos",
  downloadingEsptool: "Descargando esptool",
  unpackingEsptool: "Desempaquetando esptool",
  downloadingFirmware: "Descargando firmware",
  unpackingFirmware: "Desempaquetando firmware",
  noBoardAttached: "Ninguna placa conectada",
  scanningBoards: "Buscando placas",
  pythonNotFound: "No se ha encontrado python",
  resetingBoard: "Reiniciando placa",
  stoppingProgram: "Parando el programa",
  cannotConnectToAgent: "No se puede conectar con el agente"  
};
