/*

 Visual Blocks Language

 Copyright 2016 Google Inc.
 https://developers.google.com/blockly/

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
"use strict";Blockly.Lua=new Blockly.Generator("Lua");Blockly.Lua.addReservedWords("_,__inext,assert,bit,colors,colours,coroutine,disk,dofile,error,fs,fetfenv,getmetatable,gps,help,io,ipairs,keys,loadfile,loadstring,math,native,next,os,paintutils,pairs,parallel,pcall,peripheral,print,printError,rawequal,rawget,rawset,read,rednet,redstone,rs,select,setfenv,setmetatable,sleep,string,table,term,textutils,tonumber,tostring,turtle,type,unpack,vector,write,xpcall,_VERSION,__indext,HTTP,and,break,do,else,elseif,end,false,for,function,if,in,local,nil,not,or,repeat,return,then,true,until,while,add,sub,mul,div,mod,pow,unm,concat,len,eq,lt,le,index,newindex,call,assert,collectgarbage,dofile,error,_G,getmetatable,inpairs,load,loadfile,next,pairs,pcall,print,rawequal,rawget,rawlen,rawset,select,setmetatable,tonumber,tostring,type,_VERSION,xpcall,require,package,string,table,math,bit32,io,file,os,debug");
Blockly.Lua.ORDER_ATOMIC=0;Blockly.Lua.ORDER_HIGH=1;Blockly.Lua.ORDER_EXPONENTIATION=2;Blockly.Lua.ORDER_UNARY=3;Blockly.Lua.ORDER_MULTIPLICATIVE=4;Blockly.Lua.ORDER_ADDITIVE=5;Blockly.Lua.ORDER_CONCATENATION=6;Blockly.Lua.ORDER_RELATIONAL=7;Blockly.Lua.ORDER_AND=8;Blockly.Lua.ORDER_OR=9;Blockly.Lua.ORDER_NONE=99;
Blockly.Lua.init=function(a){Blockly.Lua.blockNums=0;Blockly.Lua.blockNum=[];Blockly.Lua.blockId=[];Blockly.Lua.definitions_=Object.create(null);Blockly.Lua.functionNames_=Object.create(null);Blockly.Lua.variableDB_?Blockly.Lua.variableDB_.reset():Blockly.Lua.variableDB_=new Blockly.Names(Blockly.Lua.RESERVED_WORDS_)};
Blockly.Lua.finish=function(a){var b=[],c;for(c in Blockly.Lua.definitions_)b.push(Blockly.Lua.definitions_[c]);delete Blockly.Lua.definitions_;delete Blockly.Lua.functionNames_;Blockly.Lua.variableDB_.reset();return b.join("\n\n")+"\n\n\n"+a};Blockly.Lua.scrubNakedValue=function(a){return"local _ = "+a+"\n"};Blockly.Lua.quote_=function(a){a=a.replace(/\\/g,"\\\\").replace(/\n/g,"\\\n").replace(/'/g,"\\'");return"'"+a+"'"};
Blockly.Lua.scrub_=function(a,b){var c="";if(!a.outputConnection||!a.outputConnection.targetConnection){var d=a.getCommentText();(d=Blockly.utils.wrap(d,Blockly.Lua.COMMENT_WRAP-3))&&(c+=Blockly.Lua.prefixLines(d,"-- ")+"\n");for(var e=0;e<a.inputList.length;e++)a.inputList[e].type==Blockly.INPUT_VALUE&&(d=a.inputList[e].connection.targetBlock())&&(d=Blockly.Lua.allNestedComments(d))&&(c+=Blockly.Lua.prefixLines(d,"-- "))}e=a.nextConnection&&a.nextConnection.targetBlock();e=Blockly.Lua.blockToCode(e);
return c+b+e};Blockly.Lua.inTryBlock=function(a){for(a=a.previousConnection;a;)if(a=a.targetBlock()){if("exception_try"==a.type)return!0;a=a.previousConnection}return!1};Blockly.Lua.blockStart=function(a,b){return Blockly.Lua.developerMode?Blockly.Lua.indent(a,"wcBlock.blockStart("+Blockly.Lua.blockIdToNum(b.id)+")")+"\n":""};Blockly.Lua.blockEnd=function(a,b){return Blockly.Lua.developerMode?Blockly.Lua.indent(a,"wcBlock.blockEnd("+Blockly.Lua.blockIdToNum(b.id)+")")+"\n":""};
Blockly.Lua.blockError=function(a,b){var c;return Blockly.Lua.developerMode?c=""+(Blockly.Lua.indent(a,"wcBlock.blockError("+Blockly.Lua.blockIdToNum(b.id)+", err, message)")+"\n"):""};Blockly.Lua.blockErrorCatched=function(a,b){var c;return Blockly.Lua.developerMode?c=""+(Blockly.Lua.indent(a,"wcBlock.blockErrorCatched("+Blockly.Lua.blockIdToNum(b.id)+")")+"\n"):""};
Blockly.Lua.tryBlock=function(a,b,c,d){var e="";Blockly.Lua.blockIdToNum(b.id);"undefined"==typeof d&&(d="");""!=d&&(e+="-- begin: "+d+"\n");!Blockly.Lua.developerMode||Blockly.Lua.inTryBlock(b)?e+=Blockly.Lua.indent(a,c):(e+=Blockly.Lua.indent(0,"try(")+"\n",e+=Blockly.Lua.indent(1,"function()")+"\n",""!=c&&(e+=Blockly.Lua.indent(2,c)),e+=Blockly.Lua.indent(1,"end,")+"\n",e+=Blockly.Lua.indent(1,"function(where, line, err, message)")+"\n",e+=Blockly.Lua.blockError(2,b),e+=Blockly.Lua.indent(1,"end")+
"\n",e+=Blockly.Lua.indent(0,")"),e=Blockly.Lua.indent(a,e)+"\n");""!=d&&(e+="-- end: "+d+"\n");b.nextConnection&&b.nextConnection.targetBlock()&&(e+="\n");return e};Blockly.Lua.require=function(a){-1==codeSection.require.indexOf('require("'+a+'")')&&codeSection.require.push('require("'+a+'")')};Blockly.Lua.indent=function(a,b){for(var c=0;c<a;c++)b=Blockly.Lua.prefixLines(b,Blockly.Lua.INDENT);return b};
Blockly.Lua.blockIdToNum=function(a){"undefined"==typeof Blockly.Lua.blockNum[a]&&(Blockly.Lua.blockNums+=1,Blockly.Lua.blockNum[a]=Blockly.Lua.blockNums,Blockly.Lua.blockId[Blockly.Lua.blockNums]=a);return Blockly.Lua.blockNum[a]};Blockly.Lua.numToBlockId=function(a){try{return Blockly.Lua.blockId[a]}catch(b){return null}};"use strict";Blockly.Lua.bitlogic={};
Blockly.Lua.bitlogic_msb=function(a){return["(("+("math.floor("+(Blockly.Lua.valueToCode(a,"BOOL",Blockly.Lua.ORDER_UNARY)||"true")+")")+" & 0xff00) >> 8)",Blockly.Lua.ORDER_UNARY]};Blockly.Lua.bitlogic_lsb=function(a){return["("+("math.floor("+(Blockly.Lua.valueToCode(a,"BOOL",Blockly.Lua.ORDER_UNARY)||"true")+")")+" & 0x00ff)",Blockly.Lua.ORDER_UNARY]};
Blockly.Lua.bitwise_op=function(a){var b=Blockly.Lua.valueToCode(a,"OP1",Blockly.Lua.ORDER_NONE),c=Blockly.Lua.valueToCode(a,"OP2",Blockly.Lua.ORDER_NONE);a=a.getFieldValue("OP");"and"==a?(b="math.floor("+b+")",a="&",c="math.floor("+c+")"):"or"==a?(b="math.floor("+b+")",a="|",c="math.floor("+c+")"):"lshift"==a?(b="math.floor("+b+")",a="<<"):"rshift"==a?(b="math.floor("+b+")",a=">>"):"xor"==a&&(b="math.floor("+b+")",a="~",c="math.floor("+c+")");return["("+b+" "+a+" "+c+")",Blockly.Lua.ORDER_UNARY]};
Blockly.Lua.bitwise_unary_op=function(a){var b=Blockly.Lua.valueToCode(a,"OP1",Blockly.Lua.ORDER_NONE);a=a.getFieldValue("OP");"not"==a&&(a="~");return["("+a+b+")",Blockly.Lua.ORDER_UNARY]};"use strict";Blockly.Lua.can={};
Blockly.Lua.can.helper={safeName:function(a){a?(a=encodeURI(a.replace(/ /g,"_")).replace(/[^\w]/g,"_"),-1!="0123456789".indexOf(a[0])&&(a="my_"+a)):a="unnamed";return a},iscan:function(a,b){return("cansetspeed"==b.type||"cansetfilter"==b.type||"canread"==b.type||"canframewrite"==b.type)&&Blockly.Lua.can.helper.name(a)==Blockly.Lua.can.helper.name(b)},isframe:function(a,b){return"canframeset"==b.type&&Blockly.Lua.valueToCode(a,"FRAME",Blockly.Lua.ORDER_NONE)==Blockly.Lua.valueToCode(b,"FRAME",Blockly.Lua.ORDER_NONE)},
hasAncestors:function(a){for(var b=a.previousConnection;b;)if(b=b.targetBlock()){if(Blockly.Lua.can.helper.iscan(a,b))return!0;b=b.previousConnection}return!1},hasFrameAncestors:function(a){for(var b=a.previousConnection;b;)if(b=b.targetBlock()){if(Blockly.Lua.can.helper.isframe(a,b))return!0;b=b.previousConnection}return!1},name:function(a){a=a.getFieldValue("MODULE");return Code.status.maps.canUnits[a]},instance:function(a){a.getFieldValue("MODULE");return"_can"+Blockly.Lua.can.helper.name(a)},
attach:function(a,b){a.getFieldValue("MODULE");var c="";Blockly.Lua.can.helper.hasAncestors(a)||(c+=Blockly.Lua.indent(0,"-- attach can bus at "+b+" khz")+"\n",c+=Blockly.Lua.indent(0,"if ("+Blockly.Lua.can.helper.instance(a)+" == nil) then")+"\n",c+=Blockly.Lua.indent(1,Blockly.Lua.can.helper.instance(a)+" = true")+"\n",c+=Blockly.Lua.indent(1,"can.attach(can."+Blockly.Lua.can.helper.name(a)+", "+b+" * 1000)")+"\n",c+=Blockly.Lua.indent(0,"end")+"\n");return c},newFrame:function(a){a.getFieldValue("MODULE");
var b=a.getFieldValue("FRAME"),c="";Blockly.Lua.can.helper.hasFrameAncestors(a)||(c+=Blockly.Lua.indent(0,"-- init frame "+b)+"\n",c+=Blockly.Lua.indent(0,Blockly.Lua.can.helper.safeName(b)+" = {}")+"\n\n",c+=Blockly.Lua.indent(0,Blockly.Lua.can.helper.safeName(b)+".id = 0")+"\n",c+=Blockly.Lua.indent(0,Blockly.Lua.can.helper.safeName(b)+".type = can.STD")+"\n",c+=Blockly.Lua.indent(0,Blockly.Lua.can.helper.safeName(b)+".len = 8")+"\n",c+=Blockly.Lua.indent(0,Blockly.Lua.can.helper.safeName(b)+".d0 = 0")+
"\n",c+=Blockly.Lua.indent(0,Blockly.Lua.can.helper.safeName(b)+".d1 = 0")+"\n",c+=Blockly.Lua.indent(0,Blockly.Lua.can.helper.safeName(b)+".d2 = 0")+"\n",c+=Blockly.Lua.indent(0,Blockly.Lua.can.helper.safeName(b)+".d3 = 0")+"\n",c+=Blockly.Lua.indent(0,Blockly.Lua.can.helper.safeName(b)+".d4 = 0")+"\n",c+=Blockly.Lua.indent(0,Blockly.Lua.can.helper.safeName(b)+".d5 = 0")+"\n",c+=Blockly.Lua.indent(0,Blockly.Lua.can.helper.safeName(b)+".d6 = 0")+"\n",c+=Blockly.Lua.indent(0,Blockly.Lua.can.helper.safeName(b)+
".d7 = 0")+"\n");return c}};Blockly.Lua.cansetspeed=function(a){a.getFieldValue("MODULE");var b=Blockly.Lua.valueToCode(a,"SPEED",Blockly.Lua.ORDER_NONE),c="",d="";Blockly.Lua.require("block");c+=Blockly.Lua.can.helper.attach(a,b);""!=c&&(c+="\r\n");return d+=Blockly.Lua.tryBlock(0,a,c,"set speed for "+Blockly.Lua.can.helper.name(a)+" speed "+b+" Kbps")};
Blockly.Lua.cansetfilter=function(a){a.getFieldValue("MODULE");var b=Blockly.Lua.valueToCode(a,"FROM",Blockly.Lua.ORDER_NONE),c=Blockly.Lua.valueToCode(a,"TO",Blockly.Lua.ORDER_NONE),d="",e="";Blockly.Lua.require("block");d+=Blockly.Lua.can.helper.attach(a,500);""!=d&&(d+="\r\n");d+=Blockly.Lua.indent(0,"can.addfilter(can."+Blockly.Lua.can.helper.name(a)+", "+b+", "+c+")")+"\n";return e+=Blockly.Lua.tryBlock(0,a,d,"add filter for "+Blockly.Lua.can.helper.name(a)+" from id "+b+" to id "+c)};
Blockly.Lua.canread=function(a){a.getFieldValue("MODULE");var b=a.getFieldValue("FRAME"),c,d="",e="";Blockly.Lua.require("block");c=""+Blockly.Lua.can.helper.attach(a,500);""!=c&&(c+="\r\n");c+=Blockly.Lua.indent(0,"-- read from "+Blockly.Lua.can.helper.name(a))+"\n";c+=Blockly.Lua.indent(0,"id, type, len, data = can.receive(can."+Blockly.Lua.can.helper.name(a)+")")+"\n\n";c+=Blockly.Lua.indent(0,"-- unpack data")+"\n";c+=Blockly.Lua.indent(0,"d0, d1, d2, d3, d4, d5, d6, d7 = string.unpack(string.rep('B', len), data)")+
"\n\n";c+=Blockly.Lua.indent(0,"-- build frame")+"\n";c+=Blockly.Lua.indent(0,"frame.id = id")+"\n";c+=Blockly.Lua.indent(0,"frame.type = type")+"\n";c+=Blockly.Lua.indent(0,"frame.len = len")+"\n";c+=Blockly.Lua.indent(0,"frame.d0 = d0")+"\n";c+=Blockly.Lua.indent(0,"frame.d1 = d1")+"\n";c+=Blockly.Lua.indent(0,"frame.d2 = d2")+"\n";c+=Blockly.Lua.indent(0,"frame.d3 = d3")+"\n";c+=Blockly.Lua.indent(0,"frame.d4 = d4")+"\n";c+=Blockly.Lua.indent(0,"frame.d5 = d5")+"\n";c+=Blockly.Lua.indent(0,"frame.d6 = d6")+
"\n";c+=Blockly.Lua.indent(0,"frame.d7 = d7")+"\n";d+=Blockly.Lua.indent(0,"-- read from CAN bus into frame "+b)+"\n";d+=Blockly.Lua.indent(0,"function _read"+Blockly.Lua.can.helper.name(a)+"_"+b+"()")+"\n";d+=Blockly.Lua.indent(1,"local id, type, len")+"\n";d+=Blockly.Lua.indent(1,"local d0, d1, d2, d3, d4, d5, d6, d7 = 0")+"\n";d+=Blockly.Lua.indent(1,"local frame = {}")+"\n\n";d+=Blockly.Lua.indent(1,Blockly.Lua.tryBlock(0,a,c));d+=Blockly.Lua.indent(1,"return frame")+"\n";d+=Blockly.Lua.indent(0,
"end")+"\n";codeSection.functions.push(d);return e+=b+" = "+Blockly.Lua.indent(0,"_read"+Blockly.Lua.can.helper.name(a)+"_"+b+"()")+"\n"};Blockly.Lua.canframeget=function(a){var b=a.getFieldValue("FIELD");return[a.getFieldValue("FRAME")+"."+b,Blockly.Lua.ORDER_HIGH]};
Blockly.Lua.canframeset=function(a){var b=a.getFieldValue("FIELD"),c=a.getFieldValue("FRAME"),d=Blockly.Lua.valueToCode(a,"VALUE",Blockly.Lua.ORDER_NONE);a=""+Blockly.Lua.can.helper.newFrame(a);""!=a&&(a+="\n");a+=Blockly.Lua.indent(0,"-- set "+b+" to frame")+"\n";return a+=Blockly.Lua.indent(0,Blockly.Lua.can.helper.safeName(c)+"."+b+" = "+d)+"\n"};
Blockly.Lua.canframewrite=function(a){a.getFieldValue("MODULE");var b=a.getFieldValue("FRAME"),c="",d="";Blockly.Lua.require("block");c+=Blockly.Lua.can.helper.attach(a,500);""!=c&&(c+="\r\n");c+=Blockly.Lua.indent(0,"can.send(can."+Blockly.Lua.can.helper.name(a)+", "+Blockly.Lua.can.helper.safeName(b)+".id, "+Blockly.Lua.can.helper.safeName(b)+".type, "+Blockly.Lua.can.helper.safeName(b)+".len, string.pack(string.rep('B', "+Blockly.Lua.can.helper.safeName(b)+".len), "+Blockly.Lua.can.helper.safeName(b)+
".d0, "+Blockly.Lua.can.helper.safeName(b)+".d1, "+Blockly.Lua.can.helper.safeName(b)+".d2, "+Blockly.Lua.can.helper.safeName(b)+".d3, "+Blockly.Lua.can.helper.safeName(b)+".d4, "+Blockly.Lua.can.helper.safeName(b)+".d5, "+Blockly.Lua.can.helper.safeName(b)+".d6, "+Blockly.Lua.can.helper.safeName(b)+".d7))")+"\n";return d+=Blockly.Lua.tryBlock(0,a,c,"write to "+Blockly.Lua.can.helper.name(a))};
Blockly.Lua.cantype=function(a){return"std"==a.getFieldValue("TYPE")?["can.STD",Blockly.Lua.ORDER_HIGH]:["can.EXT",Blockly.Lua.ORDER_HIGH]};"use strict";Blockly.Lua.colour={};Blockly.Lua.colour_picker=function(a){return["'"+a.getFieldValue("COLOUR")+"'",Blockly.Lua.ORDER_ATOMIC]};Blockly.Lua.colour_random=function(a){return['string.format("#%06x", math.random(0, 2^24 - 1))',Blockly.Lua.ORDER_HIGH]};
Blockly.Lua.colour_rgb=function(a){var b=Blockly.Lua.provideFunction_("colour_rgb",["function "+Blockly.Lua.FUNCTION_NAME_PLACEHOLDER_+"(r, g, b)","  r = math.floor(math.min(100, math.max(0, r)) * 2.55 + .5)","  g = math.floor(math.min(100, math.max(0, g)) * 2.55 + .5)","  b = math.floor(math.min(100, math.max(0, b)) * 2.55 + .5)",'  return string.format("#%02x%02x%02x", r, g, b)',"end"]),c=Blockly.Lua.valueToCode(a,"RED",Blockly.Lua.ORDER_NONE)||0,d=Blockly.Lua.valueToCode(a,"GREEN",Blockly.Lua.ORDER_NONE)||
0;a=Blockly.Lua.valueToCode(a,"BLUE",Blockly.Lua.ORDER_NONE)||0;return[b+"("+c+", "+d+", "+a+")",Blockly.Lua.ORDER_HIGH]};
Blockly.Lua.colour_blend=function(a){var b=Blockly.Lua.provideFunction_("colour_blend",["function "+Blockly.Lua.FUNCTION_NAME_PLACEHOLDER_+"(colour1, colour2, ratio)","  local r1 = tonumber(string.sub(colour1, 2, 3), 16)","  local r2 = tonumber(string.sub(colour2, 2, 3), 16)","  local g1 = tonumber(string.sub(colour1, 4, 5), 16)","  local g2 = tonumber(string.sub(colour2, 4, 5), 16)","  local b1 = tonumber(string.sub(colour1, 6, 7), 16)","  local b2 = tonumber(string.sub(colour2, 6, 7), 16)","  local ratio = math.min(1, math.max(0, ratio))",
"  local r = math.floor(r1 * (1 - ratio) + r2 * ratio + .5)","  local g = math.floor(g1 * (1 - ratio) + g2 * ratio + .5)","  local b = math.floor(b1 * (1 - ratio) + b2 * ratio + .5)",'  return string.format("#%02x%02x%02x", r, g, b)',"end"]),c=Blockly.Lua.valueToCode(a,"COLOUR1",Blockly.Lua.ORDER_NONE)||"'#000000'",d=Blockly.Lua.valueToCode(a,"COLOUR2",Blockly.Lua.ORDER_NONE)||"'#000000'";a=Blockly.Lua.valueToCode(a,"RATIO",Blockly.Lua.ORDER_NONE)||0;return[b+"("+c+", "+d+", "+a+")",Blockly.Lua.ORDER_HIGH]};
"use strict";Blockly.Lua.control={};Blockly.Lua.wait_for=function(a){var b=Blockly.Lua.valueToCode(a,"TIME",Blockly.Lua.ORDER_NONE),c=a.getFieldValue("units"),d;d=""+(Blockly.Lua.indent(0,"-- wait some time")+"\n");switch(c){case "microseconds":d+="tmr.delayus(math.floor("+b+"))\r\n";break;case "milliseconds":d+="tmr.delayms(math.floor("+b+"))\r\n";break;case "seconds":d+="tmr.delay(math.floor("+b+"))\r\n"}return Blockly.Lua.postFormat(d,a)};
Blockly.Lua.cpu_sleep=function(a){var b=Blockly.Lua.valueToCode(a,"SECONDS",Blockly.Lua.ORDER_NONE),c;c=""+Blockly.Lua.blockStart(0,a);c+=Blockly.Lua.indent(0,"-- sleep cpu some time")+"\n";return Blockly.Lua.postFormat(c+("os.sleep(math.floor("+b+"))"),a)};"use strict";Blockly.Lua.events={};
Blockly.Lua.when_board_starts=function(a){var b=Blockly.Lua.statementToCodeNoIndent(a,"DO"),c="";""!=b&&(Blockly.Lua.addDependency("block",a),c+=Blockly.Lua.indent(0,"-- when board starts")+"\n",c+=Blockly.Lua.indent(0,"thread.start(function()")+"\n",c+=Blockly.Lua.blockStart(1,a),c+=Blockly.Lua.tryBlock(1,a,b),c+=Blockly.Lua.blockEnd(1,a)+"\n",c+=Blockly.Lua.indent(1,"-- board is started, broadcast to threads that are waiting")+"\n",c+=Blockly.Lua.indent(1,"_eventBoardStarted:broadcast(false)")+
"\n",c+=Blockly.Lua.indent(0,"end)"));return Blockly.Lua.postFormat(c,a)};
Blockly.Lua.thread=function(a){var b=Blockly.Lua.statementToCodeNoIndent(a,"DO"),c="";Blockly.Lua.addDependency("block",a);c+=Blockly.Lua.indent(0,"-- thread")+"\n";c+=Blockly.Lua.indent(0,"thread.start(function()")+"\n";c+=Blockly.Lua.indent(1,"_eventBoardStarted:wait()")+"\n\n";c+=Blockly.Lua.blockStart(1,a);c+=Blockly.Lua.indent(1,"while true do")+"\n";c+=Blockly.Lua.tryBlock(2,a,b);c+=Blockly.Lua.indent(1,"end")+"\n";c+=Blockly.Lua.blockEnd(1,a);c+=Blockly.Lua.indent(0,"end)");return Blockly.Lua.postFormat(c,
a)};
Blockly.Lua.when_i_receive=function(a){var b=Blockly.Lua.statementToCodeNoIndent(a,"DO"),c=a.getFieldValue("WHEN"),d=this.workspace.eventIndexOf(c),e="",f="",g="";Blockly.Lua.addDependency("block",a);f+=Blockly.Lua.indent(0,'-- event "'+c+'" declaration')+"\n";f+=Blockly.Lua.indent(0,"_event"+d+" = event.create()")+"\n";Blockly.Lua.addCodeToSection("events",f,a);g+=Blockly.Lua.indent(0,"-- we need to wait for the completion of the board start")+"\n";g+=Blockly.Lua.indent(0,"_eventBoardStarted:wait()")+"\n\n";
g+=Blockly.Lua.indent(0,"while true do")+"\n";g+=Blockly.Lua.indent(1,'-- wait for event "'+c+'"')+"\n";g+=Blockly.Lua.indent(1,"_event"+d+":wait()")+"\n\n";g+=Blockly.Lua.blockStart(1,a);""!=b&&(g+=Blockly.Lua.indent(1,b));g+=Blockly.Lua.indent(1,"_event"+d+":done()")+"\n";g+=Blockly.Lua.blockEnd(1,a);g+=Blockly.Lua.indent(0,"end")+"\n";e+=Blockly.Lua.indent(0,"-- when I receive "+c)+"\n";e+=Blockly.Lua.indent(0,"thread.start(function()")+"\n";e+=Blockly.Lua.tryBlock(1,a,g);e+=Blockly.Lua.indent(0,
"end)");return Blockly.Lua.postFormat(e,a)};
Blockly.Lua.execute_every=function(a){var b=Blockly.Lua.statementToCodeNoIndent(a,"DO"),c=Blockly.Lua.statementToCodeNoIndent(a,"TIME"),d=a.getFieldValue("units"),e="",f="";Blockly.Lua.blockIdToNum(a.id);Blockly.Lua.addDependency("block",a);"seconds"==d&&(c[0]*=1E3);e+=Blockly.Lua.indent(0,"-- attach timer every "+c[0]+" milliseconds")+"\n";e+=Blockly.Lua.indent(0,"thread.start(function()")+"\n";e+=Blockly.Lua.indent(1,"_eventBoardStarted:wait()")+"\n\n";e+=Blockly.Lua.indent(1,"while true do")+"\n";
e+=Blockly.Lua.blockStart(2,a);""!=b&&(f+=Blockly.Lua.indent(0,b),e+=Blockly.Lua.tryBlock(2,a,f));e+=Blockly.Lua.blockEnd(2,a);e+=Blockly.Lua.indent(2,"tmr.delayms("+c[0]+")")+"\n";e+=Blockly.Lua.indent(1,"end")+"\n";e+=Blockly.Lua.indent(0,"end)");return Blockly.Lua.postFormat(e,a)};
Blockly.Lua.broadcast=function(a){var b=a.getFieldValue("WHEN"),c=this.workspace.eventIndexOf(b),d="";Blockly.Lua.addDependency("block",a);d+=Blockly.Lua.indent(0,"_event"+c+':broadcast(false)  -- boardcast "'+b+'"');return Blockly.Lua.postFormat(d,a)};
Blockly.Lua.broadcast_and_wait=function(a){var b=a.getFieldValue("WHEN"),c=this.workspace.eventIndexOf(b),d="";Blockly.Lua.addDependency("block",a);d+=Blockly.Lua.indent(0,"_event"+c+':broadcast(true)  -- boardcast and wait "'+b+'"');return Blockly.Lua.postFormat(d,a)};Blockly.Lua.event_is_being_processed=function(a){var b=a.getFieldValue("WHEN"),b=this.workspace.eventIndexOf(b);Blockly.Lua.addDependency("block",a);return["_event"+b+":pending()",Blockly.Lua.ORDER_HIGH]};"use strict";
Blockly.Lua.i2c={};
Blockly.Lua.i2c.helper={isI2c:function(a,b){return("i2csetspeed"==b.type||"i2cstartcondition"==b.type||"i2cstopcondition"==b.type||"i2caddress"==b.type||"i2cread"==b.type||"i2cwrite"==b.type)&&a.getFieldValue("MODULE")==b.getFieldValue("MODULE")},hasAncestors:function(a){for(var b=a.previousConnection;b;)if(b=b.targetBlock()){if(Blockly.Lua.i2c.helper.isI2c(a,b))return!0;b=b.previousConnection}return!1},name:function(a){a=a.getFieldValue("MODULE");return Code.status.maps.i2cUnits[a][1]},instance:function(a){a.getFieldValue("MODULE");
return"_i2c"+Blockly.Lua.i2c.helper.name(a)},attach:function(a){a.getFieldValue("MODULE");var b="";Blockly.Lua.i2c.helper.hasAncestors(a)||(b+=Blockly.Lua.indent(0,"if ("+Blockly.Lua.i2c.helper.instance(a)+" == nil) then")+"\n",b+=Blockly.Lua.indent(1,""+Blockly.Lua.i2c.helper.instance(a)+" = i2c.attach(i2c."+Blockly.Lua.i2c.helper.name(a)+", i2c.MASTER)")+"\n",b+=Blockly.Lua.indent(0,"end")+"\n\n");return b}};
Blockly.Lua.i2csetspeed=function(a){a.getFieldValue("MODULE");var b=Blockly.Lua.valueToCode(a,"SPEED",Blockly.Lua.ORDER_NONE),c="",d="";Blockly.Lua.require("block");c+=Blockly.Lua.i2c.helper.attach(a);c+=Blockly.Lua.indent(0,Blockly.Lua.i2c.helper.instance(a)+":setspeed("+b+")\n");return d+=Blockly.Lua.tryBlock(0,a,c,"set speed for "+Blockly.Lua.i2c.helper.name(a)+" speed "+b+" hz")};
Blockly.Lua.i2cstartcondition=function(a){a.getFieldValue("MODULE");var b="",c="";Blockly.Lua.require("block");b+=Blockly.Lua.i2c.helper.attach(a);b+=Blockly.Lua.indent(0,Blockly.Lua.i2c.helper.instance(a)+":start()\n");return c+=Blockly.Lua.tryBlock(0,a,b,"start condition for "+Blockly.Lua.i2c.helper.name(a))};
Blockly.Lua.i2cstopcondition=function(a){a.getFieldValue("MODULE");var b="",c="";Blockly.Lua.require("block");b+=Blockly.Lua.i2c.helper.attach(a);b+=Blockly.Lua.indent(0,Blockly.Lua.i2c.helper.instance(a)+":stop()")+"\n";return c+=Blockly.Lua.tryBlock(0,a,b,"stop condition for "+Blockly.Lua.i2c.helper.name(a))};
Blockly.Lua.i2caddress=function(a){a.getFieldValue("MODULE");var b=Blockly.Lua.valueToCode(a,"ADDRESS",Blockly.Lua.ORDER_NONE),c=a.getFieldValue("DIRECTION"),d="",e="";Blockly.Lua.require("block");d+=Blockly.Lua.i2c.helper.attach(a);d+=Blockly.Lua.indent(0,Blockly.Lua.i2c.helper.instance(a)+":address("+b+", "+("read"==c?"true":"false")+")")+"\n";return e+=Blockly.Lua.tryBlock(0,a,d,"set address "+b+" for "+Blockly.Lua.i2c.helper.name(a)+" for "+c)};
Blockly.Lua.i2cread=function(a){a.getFieldValue("MODULE");var b,c="",d="";Blockly.Lua.require("block");b=""+Blockly.Lua.i2c.helper.attach(a);b+=Blockly.Lua.indent(0,"-- read from "+Blockly.Lua.i2c.helper.name(a))+"\n";b+=Blockly.Lua.indent(0,"val = "+Blockly.Lua.i2c.helper.instance(a)+":read()")+"\n";c+=Blockly.Lua.indent(0,"function _read"+Blockly.Lua.i2c.helper.name(a)+"()")+"\n";c+=Blockly.Lua.indent(1,"local val")+"\n\n";c+=Blockly.Lua.indent(1,Blockly.Lua.tryBlock(0,a,b))+"\n";c+=Blockly.Lua.indent(1,
"return val")+"\n";c+=Blockly.Lua.indent(0,"end")+"\n";codeSection.functions.push(c);d+=Blockly.Lua.indent(0,"_read"+Blockly.Lua.i2c.helper.name(a)+"()")+"\n";a.nextConnection&&(d+="\n");return[d,Blockly.Lua.ORDER_HIGH]};
Blockly.Lua.i2cwrite=function(a){a.getFieldValue("MODULE");var b=Blockly.Lua.valueToCode(a,"VALUE",Blockly.Lua.ORDER_NONE),c="",d="";Blockly.Lua.require("block");c+=Blockly.Lua.i2c.helper.attach(a);c+=Blockly.Lua.indent(0,Blockly.Lua.i2c.helper.instance(a)+":write("+b+")")+"\n";return d+=Blockly.Lua.tryBlock(0,a,c,"write "+b+" to "+Blockly.Lua.i2c.helper.name(a))};"use strict";Blockly.Lua.io={};
Blockly.Lua.io.helper={isDigital:function(a,b,c){return c?"setdigitalpin"==b.type&&a.getFieldValue("PIN")==b.getFieldValue("PIN"):"getdigitalpin"==b.type&&a.getFieldValue("PIN")==b.getFieldValue("PIN")},nameDigital:function(a,b){"undefined"==typeof b&&(b="PIN");var c=Blockly.Lua.statementToCodeNoIndent(a,b)[0];"undefined"==typeof c&&(c=a.getFieldValue(b));return c},instanceDigital:function(a,b){"undefined"==typeof b&&(b="PIN");var c=Blockly.Lua.statementToCodeNoIndent(a,b)[0];"undefined"==typeof c&&
(c=a.getFieldValue(b));0===c.indexOf("pio.")&&(c=c.replace("pio.",""));return"_pio_"+c},hasPullUp:function(a,b){"undefined"==typeof b&&(b="PIN");var c=Blockly.Lua.statementToCodeNoIndent(a,b)[0];"undefined"==typeof c&&(c=a.getFieldValue(b));0===c.indexOf("pio.")&&(c=c.replace("pio.",""));return Blockly.Blocks.io.helper.pinHasPullUp(c)},hasPullDown:function(a,b){"undefined"==typeof b&&(b="PIN");var c=Blockly.Lua.statementToCodeNoIndent(a,b)[0];"undefined"==typeof c&&(c=a.getFieldValue(b));0===c.indexOf("pio.")&&
(c=c.replace("pio.",""));return Blockly.Blocks.io.helper.pinHasPullDown(c)},attachDigital:function(a,b){var c;c=""+(Blockly.Lua.indent(0,"if (("+Blockly.Lua.io.helper.instanceDigital(a)+" == nil) or ("+Blockly.Lua.io.helper.instanceDigital(a)+" == "+(b?"pio.INPUT":"pio.OUTPUT")+")) then")+"\n");c+=Blockly.Lua.indent(1,Blockly.Lua.io.helper.instanceDigital(a)+" = ")+(b?"pio.OUTPUT":"pio.INPUT")+"\n";b?(c+=Blockly.Lua.indent(1,"pio.pin.setdir(pio.OUTPUT, "+Blockly.Lua.io.helper.nameDigital(a)+")")+
"\n",Blockly.Lua.io.helper.hasPullUp(a)|Blockly.Lua.io.helper.hasPullDown(a)&&(c+=Blockly.Lua.indent(1,"pio.pin.setpull(pio.NOPULL, "+Blockly.Lua.io.helper.nameDigital(a)+")")+"\n")):(c+=Blockly.Lua.indent(1,"pio.pin.setdir(pio.INPUT, "+Blockly.Lua.io.helper.nameDigital(a)+")")+"\n",Blockly.Lua.io.helper.hasPullUp(a)&&(c+=Blockly.Lua.indent(1,"pio.pin.setpull(pio.PULLUP, "+Blockly.Lua.io.helper.nameDigital(a)+")")+"\n"));return c+=Blockly.Lua.indent(0,"end")+"\n\n"},isAnalog:function(a,b){return"getanalogpin"==
b.type&&a.getFieldValue("PIN")==b.getFieldValue("PIN")},isExternalAnalog:function(a,b){return"getexternalanalogchannel"==b.type&&a.getFieldValue("UNIT")==b.getFieldValue("UNIT")&&a.getFieldValue("CHANNEL")==b.getFieldValue("CHANNEL")},hasAncestorsAnalog:function(a){for(var b=a.previousConnection;b;)if(b=b.targetBlock()){if(Blockly.Lua.io.helper.isAnalog(a,b))return!0;b=b.previousConnection}return!1},hasAncestorsExternalAnalog:function(a){for(var b=a.previousConnection;b;)if(b=b.targetBlock()){if(Blockly.Lua.io.helper.isExternalAnalog(a,
b))return!0;b=b.previousConnection}return!1},nameAnalog:function(a){a=Blockly.Lua.statementToCodeNoIndent(a,"PIN")[0];0===a.indexOf("pio.")&&(a=a.replace("pio.",""));return a},nameExternalAnalog:function(a){var b=Blockly.Lua.statementToCodeNoIndent(a,"UNIT")[0];a=Blockly.Lua.statementToCodeNoIndent(a,"CHANNEL")[0];return b.replace("adc.","")+"_"+a},instanceAnalog:function(a){return"_adc_"+Blockly.Lua.io.helper.nameAnalog(a)},instanceExternalAnalog:function(a){return"_adc_"+Blockly.Lua.io.helper.nameExternalAnalog(a)},
attachAnalog:function(a){var b="";Blockly.Lua.io.helper.hasAncestorsAnalog(a)||(b+=Blockly.Lua.indent(0,"if ("+Blockly.Lua.io.helper.instanceAnalog(a)+" == nil) then")+"\n",b+=Blockly.Lua.indent(1,Blockly.Lua.io.helper.instanceAnalog(a)+" = adc.attach(adc.ADC1, "+Blockly.Lua.io.helper.nameDigital(a)+", 12)")+"\n",b+=Blockly.Lua.indent(0,"end")+"\n");return b},attachExternalAnalog:function(a){var b="",c=Blockly.Lua.statementToCodeNoIndent(a,"UNIT")[0],d=Blockly.Lua.statementToCodeNoIndent(a,"CHANNEL")[0],
e=12,f;for(f in Code.status.maps.externalAdcUnits)Code.status.maps.externalAdcUnits[f][0]==c.replace("adc.","")&&(e=Code.status.maps.externalAdcUnits[f][2]);Blockly.Lua.io.helper.hasAncestorsExternalAnalog(a)||(b+=Blockly.Lua.indent(0,"if ("+Blockly.Lua.io.helper.instanceExternalAnalog(a)+" == nil) then")+"\n",b+=Blockly.Lua.indent(1,Blockly.Lua.io.helper.instanceExternalAnalog(a)+" = adc.attach("+c+","+d+","+e+")")+"\n",b+=Blockly.Lua.indent(0,"end")+"\n");return b},isPwm:function(a,b){return"setpwmpin"==
b.type&&a.getFieldValue("PIN")==b.getFieldValue("PIN")},hasAncestorsPwm:function(a){for(var b=a.previousConnection;b;)if(b=b.targetBlock()){if(Blockly.Lua.io.helper.isPwm(a,b))return!0;b=b.previousConnection}return!1},namePwm:function(a){a=Blockly.Lua.statementToCodeNoIndent(a,"PIN")[0];0===a.indexOf("pio.")&&(a=a.replace("pio.",""));return a},instancePwm:function(a){return"_pwm"+Blockly.Lua.io.helper.namePwm(a)},attachPwm:function(a){var b=Blockly.Lua.valueToCode(a,"FREQUENCY",Blockly.Lua.ORDER_NONE)||
"''",c=Blockly.Lua.valueToCode(a,"DUTY",Blockly.Lua.ORDER_NONE)||"''",d="";Blockly.Lua.io.helper.hasAncestorsPwm(a)?(d+=Blockly.Lua.indent(0,Blockly.Lua.io.helper.instancePwm(a)+":setfreq("+b+")")+"\n",d+=Blockly.Lua.indent(0,Blockly.Lua.io.helper.instancePwm(a)+":setduty("+c+" * 0.01)")+"\n"):(d+=Blockly.Lua.indent(0,"if ("+Blockly.Lua.io.helper.instancePwm(a)+" == nil) then")+"\n",d+=Blockly.Lua.indent(1,Blockly.Lua.io.helper.instancePwm(a)+" = pwm.attach("+Blockly.Lua.io.helper.nameDigital(a)+
", "+b+", ("+c+") * 0.01)")+"\n",d+=Blockly.Lua.indent(1,Blockly.Lua.io.helper.instancePwm(a)+":start()")+"\n",d+=Blockly.Lua.indent(0,"else")+"\n",d+=Blockly.Lua.indent(1,Blockly.Lua.io.helper.instancePwm(a)+":setfreq("+b+")")+"\n",d+=Blockly.Lua.indent(1,Blockly.Lua.io.helper.instancePwm(a)+":setduty("+c+" * 0.01)")+"\n",d+=Blockly.Lua.indent(0,"end")+"\n");return d}};
Blockly.Lua.setdigitalpin=function(a){var b=a.getFieldValue("VALUE"),c="",d="";Blockly.Lua.require("block");c+=Blockly.Lua.io.helper.attachDigital(a,!0);c+=Blockly.Lua.indent(0,"pio.pin.setval("+b+", "+Blockly.Lua.io.helper.nameDigital(a)+")")+"\n";return d+=Blockly.Lua.tryBlock(0,a,c,"set digital pin "+Blockly.Lua.io.helper.nameDigital(a)+" to "+b)};
Blockly.Lua.invertdigitalpin=function(a){a.getFieldValue("VALUE");var b="",c="";Blockly.Lua.require("block");b+=Blockly.Lua.io.helper.attachDigital(a,!0);b+=Blockly.Lua.indent(0,"pio.pin.inv("+Blockly.Lua.io.helper.nameDigital(a)+")")+"\n";return c+=Blockly.Lua.tryBlock(0,a,b,"invert digital pin value "+Blockly.Lua.io.helper.nameDigital(a))};
Blockly.Lua.getdigitalpin=function(a){var b,c="",d="";Blockly.Lua.require("block");b=""+Blockly.Lua.io.helper.attachDigital(a,!1);b+=Blockly.Lua.indent(0,"val = pio.pin.getval("+Blockly.Lua.io.helper.nameDigital(a)+")")+"\n";c+=Blockly.Lua.indent(0,"function _getDigitalPin"+Blockly.Lua.io.helper.instanceDigital(a)+"()")+"\n";c+=Blockly.Lua.indent(1,"local val")+"\n\n";c+=Blockly.Lua.indent(1,Blockly.Lua.tryBlock(0,a,b))+"\n";c+=Blockly.Lua.indent(1,"return val")+"\n";c+=Blockly.Lua.indent(0,"end")+
"\n";codeSection.functions.push(c);d+=Blockly.Lua.indent(0,"_getDigitalPin"+Blockly.Lua.io.helper.instanceDigital(a)+"()");return[d,Blockly.Lua.ORDER_HIGH]};
Blockly.Lua.getanalogpin=function(a){var b=a.getFieldValue("FORMAT"),c,d="",e="";Blockly.Lua.require("block");c=""+Blockly.Lua.io.helper.attachAnalog(a,!1);d+=Blockly.Lua.indent(0,"-- get analog pin value "+Blockly.Lua.io.helper.nameAnalog(a))+" \n";d+=Blockly.Lua.indent(0,"function _getAnalogPin_"+Blockly.Lua.io.helper.nameAnalog(a)+"_"+b+"()")+"\n";d+=Blockly.Lua.indent(1,"local raw = nil")+"\n";d+=Blockly.Lua.indent(1,"local mvolts = nil")+"\n\n";d+=Blockly.Lua.indent(1,Blockly.Lua.tryBlock(0,
a,c))+"\n";d+=Blockly.Lua.indent(1,"raw, mvolts = "+Blockly.Lua.io.helper.instanceAnalog(a)+":read()")+"\n";d="mvolts"==b?d+(Blockly.Lua.indent(1,"val = mvolts")+"\n\n"):d+(Blockly.Lua.indent(1,"val = raw")+"\n\n");d+=Blockly.Lua.indent(1,"return val")+"\n";d+=Blockly.Lua.indent(0,"end")+"\n";codeSection.functions.push(d);e+=Blockly.Lua.indent(0,"_getAnalogPin_"+Blockly.Lua.io.helper.nameAnalog(a)+"_"+b+"()");return[e,Blockly.Lua.ORDER_HIGH]};
Blockly.Lua.getexternalanalogchannel=function(a){var b=a.getFieldValue("FORMAT"),c,d="",e="";Blockly.Lua.require("block");c=""+Blockly.Lua.io.helper.attachExternalAnalog(a,!1);d+=Blockly.Lua.indent(0,"function _getAnalogPin_"+Blockly.Lua.io.helper.nameExternalAnalog(a)+"_"+b+"()")+"\n";d+=Blockly.Lua.indent(1,"local raw = nil")+"\n";d+=Blockly.Lua.indent(1,"local mvolts = nil")+"\n\n";d+=Blockly.Lua.indent(1,Blockly.Lua.tryBlock(0,a,c))+"\n";d+=Blockly.Lua.indent(1,"raw, mvolts = "+Blockly.Lua.io.helper.instanceExternalAnalog(a)+
":read()")+"\n";d="mvolts"==b?d+(Blockly.Lua.indent(1,"val = mvolts")+"\n\n"):d+(Blockly.Lua.indent(1,"val = raw")+"\n\n");d+=Blockly.Lua.indent(1,"return val")+"\n";d+=Blockly.Lua.indent(0,"end")+"\n";codeSection.functions.push(d);e+=Blockly.Lua.indent(0,"_getAnalogPin_"+Blockly.Lua.io.helper.nameExternalAnalog(a)+"_"+b+"()");return[e,Blockly.Lua.ORDER_HIGH]};Blockly.Lua.output_digital_pin=function(a){a=a.getFieldValue("PIN");return["pio."+Code.status.maps.digitalPins[a][0],Blockly.Lua.ORDER_HIGH]};
Blockly.Lua.output_digital_pin_sel=function(a){a=a.getFieldValue("PIN");return["pio."+Code.status.maps.digitalPins[a][0],Blockly.Lua.ORDER_HIGH]};Blockly.Lua.input_digital_pin=function(a){a=a.getFieldValue("PIN");return["pio."+Code.status.maps.digitalPins[a][0],Blockly.Lua.ORDER_HIGH]};Blockly.Lua.input_digital_pin_sel=function(a){a=a.getFieldValue("PIN");return["pio."+Code.status.maps.digitalPins[a][0],Blockly.Lua.ORDER_HIGH]};
Blockly.Lua.pwm_pins=function(a){a=a.getFieldValue("PIN");return["pio."+Code.status.maps.digitalPins[a][0],Blockly.Lua.ORDER_HIGH]};Blockly.Lua.pwm_pins_sel=function(a){a=a.getFieldValue("PIN");return["pio."+Code.status.maps.digitalPins[a][0],Blockly.Lua.ORDER_HIGH]};Blockly.Lua.analog_pins=function(a){a=a.getFieldValue("PIN");return["pio."+Code.status.maps.digitalPins[a][0],Blockly.Lua.ORDER_HIGH]};
Blockly.Lua.analog_pins_sel=function(a){a=a.getFieldValue("PIN");return["pio."+Code.status.maps.digitalPins[a][0],Blockly.Lua.ORDER_HIGH]};Blockly.Lua.uart_units=function(a){a=a.getFieldValue("UNIT");return["uart."+Code.status.maps.uartUnits[a][1],Blockly.Lua.ORDER_HIGH]};Blockly.Lua.external_analog_units=function(a){a=a.getFieldValue("UNIT");return["adc."+Code.status.maps.externalAdcUnits[a][0],Blockly.Lua.ORDER_HIGH]};
Blockly.Lua.external_analog_channels=function(a){return[a.getFieldValue("CHANNEL"),Blockly.Lua.ORDER_HIGH]};Blockly.Lua.setpwmpin=function(a){var b=Blockly.Lua.valueToCode(a,"FREQUENCY",Blockly.Lua.ORDER_NONE)||"''",c=Blockly.Lua.valueToCode(a,"DUTY",Blockly.Lua.ORDER_NONE)||"''",d="",e="";Blockly.Lua.require("block");d+=Blockly.Lua.io.helper.attachPwm(a);return e+=Blockly.Lua.tryBlock(0,a,d,"set pwm pin "+Blockly.Lua.io.helper.namePwm(a)+" to freq "+b+" hz, duty ("+c+")%")};
Blockly.Lua.when_digital_pin=function(a){var b=Blockly.Lua.statementToCodeNoIndent(a,"DO"),c=a.getFieldValue("WHEN"),d="",e="";Blockly.Lua.require("block");d+=Blockly.Lua.indent(0,"-- we need to wait for the completion of the board start")+"\n";d+=Blockly.Lua.indent(0,"_eventBoardStarted:wait()")+"\n\n";d+=Blockly.Lua.io.helper.attachDigital(a,!1);d+=Blockly.Lua.indent(0,"pio.pin.interrupt("+Blockly.Lua.io.helper.nameDigital(a)+", function()")+"\n";d+=Blockly.Lua.blockStart(1,a);""!=b&&(d+=Blockly.Lua.indent(1,
b));d+=Blockly.Lua.blockEnd(1,a);d+=Blockly.Lua.indent(0,"end, pio.pin."+c+")")+"\n";e+=Blockly.Lua.indent(0,"thread.start(function()")+"\n";e+=Blockly.Lua.tryBlock(1,a,d);return e+=Blockly.Lua.indent(0,"end)")+"\n"};"use strict";Blockly.Lua.lists={};Blockly.Lua.lists_create_empty=function(a){return["{}",Blockly.Lua.ORDER_ATOMIC]};
Blockly.Lua.lists_create_with=function(a){for(var b=Array(a.itemCount_),c=0;c<a.itemCount_;c++)b[c]=Blockly.Lua.valueToCode(a,"ADD"+c,Blockly.Lua.ORDER_NONE)||"None";return["{"+b.join(", ")+"}",Blockly.Lua.ORDER_ATOMIC]};
Blockly.Lua.lists_repeat=function(a){var b=Blockly.Lua.provideFunction_("create_list_repeated",["function "+Blockly.Lua.FUNCTION_NAME_PLACEHOLDER_+"(item, count)","  local t = {}","  for i = 1, count do","    table.insert(t, item)","  end","  return t","end"]),c=Blockly.Lua.valueToCode(a,"ITEM",Blockly.Lua.ORDER_NONE)||"None";a=Blockly.Lua.valueToCode(a,"NUM",Blockly.Lua.ORDER_NONE)||"0";return[b+"("+c+", "+a+")",Blockly.Lua.ORDER_HIGH]};
Blockly.Lua.lists_length=function(a){return["#"+(Blockly.Lua.valueToCode(a,"VALUE",Blockly.Lua.ORDER_UNARY)||"{}"),Blockly.Lua.ORDER_UNARY]};Blockly.Lua.lists_isEmpty=function(a){return["#"+(Blockly.Lua.valueToCode(a,"VALUE",Blockly.Lua.ORDER_UNARY)||"{}")+" == 0",Blockly.Lua.ORDER_RELATIONAL]};
Blockly.Lua.lists_indexOf=function(a){var b=Blockly.Lua.valueToCode(a,"FIND",Blockly.Lua.ORDER_NONE)||"''",c=Blockly.Lua.valueToCode(a,"VALUE",Blockly.Lua.ORDER_NONE)||"{}";return[("FIRST"==a.getFieldValue("END")?Blockly.Lua.provideFunction_("first_index",["function "+Blockly.Lua.FUNCTION_NAME_PLACEHOLDER_+"(t, elem)","  for k, v in ipairs(t) do","    if v == elem then","      return k","    end","  end","  return 0","end"]):Blockly.Lua.provideFunction_("last_index",["function "+Blockly.Lua.FUNCTION_NAME_PLACEHOLDER_+
"(t, elem)","  for i = #t, 1, -1 do","    if t[i] == elem then","      return i","    end","  end","  return 0","end"]))+"("+c+", "+b+")",Blockly.Lua.ORDER_HIGH]};Blockly.Lua.lists.getIndex_=function(a,b,c){return"FIRST"==b?"1":"FROM_END"==b?"#"+a+" + 1 - "+c:"LAST"==b?"#"+a:"RANDOM"==b?"math.random(#"+a+")":c};
Blockly.Lua.lists_getIndex=function(a){var b=a.getFieldValue("MODE")||"GET",c=a.getFieldValue("WHERE")||"FROM_START",d=Blockly.Lua.valueToCode(a,"VALUE",Blockly.Lua.ORDER_HIGH)||"{}",e=Blockly.Lua.lists.getIndex_;if("LAST"!=c&&"FROM_END"!=c&&"RANDOM"!=c||d.match(/^\w+$/)){f="GET"==b&&"FROM_END"==c?Blockly.Lua.ORDER_ADDITIVE:Blockly.Lua.ORDER_NONE;a=Blockly.Lua.valueToCode(a,"AT",f)||"1";a=e(d,c,a);if("GET"==b)return[d+"["+a+"]",Blockly.Lua.ORDER_HIGH];c="table.remove("+d+", "+a+")";return"GET_REMOVE"==
b?[c,Blockly.Lua.ORDER_HIGH]:c+"\n"}if("REMOVE"==b){var f="FROM_END"==c?Blockly.Lua.ORDER_ADDITIVE:Blockly.Lua.ORDER_NONE;a=Blockly.Lua.valueToCode(a,"AT",f)||"1";b=Blockly.Lua.variableDB_.getDistinctName("tmp_list",Blockly.Variables.NAME_TYPE);a=e(b,c,a);return b+" = "+d+"\ntable.remove("+b+", "+a+")\n"}a=Blockly.Lua.valueToCode(a,"AT",Blockly.Lua.ORDER_NONE)||"1";return[("GET"==b?Blockly.Lua.provideFunction_("list_get_"+c.toLowerCase(),["function "+Blockly.Lua.FUNCTION_NAME_PLACEHOLDER_+"(t"+("FROM_END"==
c||"FROM_START"==c?", at)":")"),"  return t["+e("t",c,"at")+"]","end"]):Blockly.Lua.provideFunction_("list_remove_"+c.toLowerCase(),["function "+Blockly.Lua.FUNCTION_NAME_PLACEHOLDER_+"(t"+("FROM_END"==c||"FROM_START"==c?", at)":")"),"  return table.remove(t, "+e("t",c,"at")+")","end"]))+"("+d+("FROM_END"==c||"FROM_START"==c?", "+a:"")+")",Blockly.Lua.ORDER_HIGH]};
Blockly.Lua.lists_setIndex=function(a){var b=Blockly.Lua.valueToCode(a,"LIST",Blockly.Lua.ORDER_HIGH)||"{}",c=a.getFieldValue("MODE")||"SET",d=a.getFieldValue("WHERE")||"FROM_START",e=Blockly.Lua.valueToCode(a,"AT",Blockly.Lua.ORDER_ADDITIVE)||"1";a=Blockly.Lua.valueToCode(a,"TO",Blockly.Lua.ORDER_NONE)||"None";var f=Blockly.Lua.lists.getIndex_,g="";if(("LAST"==d||"FROM_END"==d||"RANDOM"==d)&&!b.match(/^\w+$/))var k=Blockly.Lua.variableDB_.getDistinctName("tmp_list",Blockly.Variables.NAME_TYPE),g=
k+" = "+b+"\n",b=k;g="SET"==c?g+(b+"["+f(b,d,e)+"] = "+a):g+("table.insert("+b+", "+(f(b,d,e)+("LAST"==d?" + 1":""))+", "+a+")");return g+"\n"};
Blockly.Lua.lists_getSublist=function(a){var b=Blockly.Lua.valueToCode(a,"LIST",Blockly.Lua.ORDER_NONE)||"{}",c=a.getFieldValue("WHERE1"),d=a.getFieldValue("WHERE2"),e=Blockly.Lua.valueToCode(a,"AT1",Blockly.Lua.ORDER_NONE)||"1";a=Blockly.Lua.valueToCode(a,"AT2",Blockly.Lua.ORDER_NONE)||"1";var f=Blockly.Lua.lists.getIndex_;return[Blockly.Lua.provideFunction_("list_sublist_"+c.toLowerCase()+"_"+d.toLowerCase(),["function "+Blockly.Lua.FUNCTION_NAME_PLACEHOLDER_+"(source"+("FROM_END"==c||"FROM_START"==
c?", at1":"")+("FROM_END"==d||"FROM_START"==d?", at2":"")+")","  local t = {}","  local start = "+f("source",c,"at1"),"  local finish = "+f("source",d,"at2"),"  for i = start, finish do","    table.insert(t, source[i])","  end","  return t","end"])+"("+b+("FROM_END"==c||"FROM_START"==c?", "+e:"")+("FROM_END"==d||"FROM_START"==d?", "+a:"")+")",Blockly.Lua.ORDER_HIGH]};
Blockly.Lua.lists_sort=function(a){var b=Blockly.Lua.valueToCode(a,"LIST",Blockly.Lua.ORDER_NONE)||"{}",c="1"===a.getFieldValue("DIRECTION")?1:-1;a=a.getFieldValue("TYPE");return[Blockly.Lua.provideFunction_("list_sort",["function "+Blockly.Lua.FUNCTION_NAME_PLACEHOLDER_+"(list, typev, direction)","  local t = {}","  for n,v in pairs(list) do table.insert(t, v) end","  local compareFuncs = {","    NUMERIC = function(a, b)","      return (tonumber(tostring(a)) or 0)","          < (tonumber(tostring(b)) or 0) end,",
"    TEXT = function(a, b)","      return tostring(a) < tostring(b) end,","    IGNORE_CASE = function(a, b)","      return string.lower(tostring(a)) < string.lower(tostring(b)) end","  }","  local compareTemp = compareFuncs[typev]","  local compare = compareTemp","  if direction == -1","  then compare = function(a, b) return compareTemp(b, a) end","  end","  table.sort(t, compare)","  return t","end"])+"("+b+',"'+a+'", '+c+")",Blockly.Lua.ORDER_HIGH]};
Blockly.Lua.lists_split=function(a){var b=Blockly.Lua.valueToCode(a,"INPUT",Blockly.Lua.ORDER_NONE),c=Blockly.Lua.valueToCode(a,"DELIM",Blockly.Lua.ORDER_NONE)||"''";a=a.getFieldValue("MODE");if("SPLIT"==a)b||(b="''"),a=Blockly.Lua.provideFunction_("list_string_split",["function "+Blockly.Lua.FUNCTION_NAME_PLACEHOLDER_+"(input, delim)","  local t = {}","  local pos = 1","  while true do","    next_delim = string.find(input, delim, pos)","    if next_delim == nil then","      table.insert(t, string.sub(input, pos))",
"      break","    else","      table.insert(t, string.sub(input, pos, next_delim-1))","      pos = next_delim + #delim","    end","  end","  return t","end"]);else if("JOIN"==a)b||(b="{}"),a="table.concat";else throw"Unknown mode: "+a;return[a+"("+b+", "+c+")",Blockly.Lua.ORDER_HIGH]};"use strict";Blockly.Lua.logic={};
Blockly.Lua.controls_if=function(a){var b=0,c="",d,e;do e=Blockly.Lua.valueToCode(a,"IF"+b,Blockly.Lua.ORDER_NONE)||"false",d=Blockly.Lua.statementToCode(a,"DO"+b),c+=(0<b?"else":"")+"if "+e+" then\n"+d,++b;while(a.getInput("IF"+b));a.getInput("ELSE")&&(d=Blockly.Lua.statementToCode(a,"ELSE"),c+="else\n"+d);return c+"end\n"};Blockly.Lua.controls_ifelse=Blockly.Lua.controls_if;
Blockly.Lua.logic_compare=function(a){var b={EQ:"==",NEQ:"~=",LT:"<",LTE:"<=",GT:">",GTE:">="}[a.getFieldValue("OP")],c=Blockly.Lua.valueToCode(a,"A",Blockly.Lua.ORDER_RELATIONAL)||"0";a=Blockly.Lua.valueToCode(a,"B",Blockly.Lua.ORDER_RELATIONAL)||"0";return[c+" "+b+" "+a,Blockly.Lua.ORDER_RELATIONAL]};
Blockly.Lua.logic_operation=function(a){var b="AND"==a.getFieldValue("OP")?"and":"or",c="and"==b?Blockly.Lua.ORDER_AND:Blockly.Lua.ORDER_OR,d=Blockly.Lua.valueToCode(a,"A",c);a=Blockly.Lua.valueToCode(a,"B",c);if(d||a){var e="and"==b?"true":"false";d||(d=e);a||(a=e)}else a=d="false";return[d+" "+b+" "+a,c]};Blockly.Lua.logic_negate=function(a){return["not "+(Blockly.Lua.valueToCode(a,"BOOL",Blockly.Lua.ORDER_UNARY)||"true"),Blockly.Lua.ORDER_UNARY]};
Blockly.Lua.logic_boolean=function(a){return["TRUE"==a.getFieldValue("BOOL")?"true":"false",Blockly.Lua.ORDER_ATOMIC]};Blockly.Lua.logic_null=function(a){return["nil",Blockly.Lua.ORDER_ATOMIC]};Blockly.Lua.logic_ternary=function(a){var b=Blockly.Lua.valueToCode(a,"IF",Blockly.Lua.ORDER_AND)||"false",c=Blockly.Lua.valueToCode(a,"THEN",Blockly.Lua.ORDER_AND)||"nil";a=Blockly.Lua.valueToCode(a,"ELSE",Blockly.Lua.ORDER_OR)||"nil";return[b+" and "+c+" or "+a,Blockly.Lua.ORDER_OR]};"use strict";
Blockly.Lua.loops={};Blockly.Lua.CONTINUE_STATEMENT="goto continue\n";Blockly.Lua.addContinueLabel=function(a){return-1<a.indexOf(Blockly.Lua.CONTINUE_STATEMENT)?a+Blockly.Lua.INDENT+"::continue::\n":a};Blockly.Lua.controls_repeat=function(a){var b=parseInt(a.getFieldValue("TIMES"),10);a=Blockly.Lua.statementToCode(a,"DO")||"";a=Blockly.Lua.addContinueLabel(a);return"for "+Blockly.Lua.variableDB_.getDistinctName("count",Blockly.Variables.NAME_TYPE)+" = 1, "+b+" do\n"+a+"end\n"};
Blockly.Lua.controls_repeat_ext=function(a){var b=Blockly.Lua.valueToCode(a,"TIMES",Blockly.Lua.ORDER_NONE)||"0",b=Blockly.isNumber(b)?parseInt(b,10):"math.floor("+b+")";a=Blockly.Lua.statementToCode(a,"DO")||"\n";a=Blockly.Lua.addContinueLabel(a);return"for "+Blockly.Lua.variableDB_.getDistinctName("count",Blockly.Variables.NAME_TYPE)+" = 1, "+b+" do\n"+a+"end\n"};
Blockly.Lua.controls_whileUntil=function(a){var b="UNTIL"==a.getFieldValue("MODE"),c=Blockly.Lua.valueToCode(a,"BOOL",b?Blockly.Lua.ORDER_UNARY:Blockly.Lua.ORDER_NONE)||"false",d=Blockly.Lua.statementToCode(a,"DO")||"\n",d=Blockly.Lua.addLoopTrap(d,a.id),d=Blockly.Lua.addContinueLabel(d);b&&(c="not "+c);return"while "+c+" do\n"+d+"end\n"};
Blockly.Lua.controls_for=function(a){var b=Blockly.Lua.variableDB_.getName(a.getFieldValue("VAR"),Blockly.Variables.NAME_TYPE),c=Blockly.Lua.valueToCode(a,"FROM",Blockly.Lua.ORDER_NONE)||"0",d=Blockly.Lua.valueToCode(a,"TO",Blockly.Lua.ORDER_NONE)||"0",e=Blockly.Lua.valueToCode(a,"BY",Blockly.Lua.ORDER_NONE)||"1",f=Blockly.Lua.statementToCode(a,"DO")||"\n",f=Blockly.Lua.addLoopTrap(f,a.id),f=Blockly.Lua.addContinueLabel(f);a="";var g;Blockly.isNumber(c)&&Blockly.isNumber(d)&&Blockly.isNumber(e)?(g=
parseFloat(c)<=parseFloat(d),e=Math.abs(parseFloat(e)),g=(g?"":"-")+e):(a="",g=Blockly.Lua.variableDB_.getDistinctName(b+"_inc",Blockly.Variables.NAME_TYPE),a+=g+" = ",a=Blockly.isNumber(e)?a+(Math.abs(e)+"\n"):a+("math.abs("+e+")\n"),a=a+("if ("+c+") > ("+d+") then\n")+(Blockly.Lua.INDENT+g+" = -"+g+"\n"),a+="end\n");return a+("for "+b+" = "+c+", "+d+", "+g)+(" do\n"+f+"end\n")};
Blockly.Lua.controls_forEach=function(a){var b=Blockly.Lua.variableDB_.getName(a.getFieldValue("VAR"),Blockly.Variables.NAME_TYPE),c=Blockly.Lua.valueToCode(a,"LIST",Blockly.Lua.ORDER_NONE)||"{}";a=Blockly.Lua.statementToCode(a,"DO")||"\n";a=Blockly.Lua.addContinueLabel(a);return"for _, "+b+" in ipairs("+c+") do \n"+a+"end\n"};
Blockly.Lua.controls_flow_statements=function(a){switch(a.getFieldValue("FLOW")){case "BREAK":return"break\n";case "CONTINUE":return Blockly.Lua.CONTINUE_STATEMENT}throw"Unknown flow statement.";};"use strict";Blockly.Lua.lora={};Blockly.Lua.lora_configure=function(a){return"lora.attach("+a.getFieldValue("BAND")+")\n"};Blockly.Lua.lora_set_devaddr=function(a){return"lora.setDevAddr("+(Blockly.Lua.valueToCode(a,"DEVADDR",Blockly.Lua.ORDER_NONE)||"''")+")\n"};
Blockly.Lua.lora_set_nwkskey=function(a){return"lora.setNwksKey("+(Blockly.Lua.valueToCode(a,"NWKSKEY",Blockly.Lua.ORDER_NONE)||"''")+")\n"};Blockly.Lua.lora_set_appskey=function(a){return"lora.setAppsKey("+(Blockly.Lua.valueToCode(a,"APPSKEY",Blockly.Lua.ORDER_NONE)||"''")+")\n"};Blockly.Lua.lora_set_deveui=function(a){return"lora.setDevEui("+(Blockly.Lua.valueToCode(a,"DEVEUI",Blockly.Lua.ORDER_NONE)||"''")+")\n"};
Blockly.Lua.lora_set_appeui=function(a){return"lora.setAppEui("+(Blockly.Lua.valueToCode(a,"APPEUI",Blockly.Lua.ORDER_NONE)||"''")+")\n"};Blockly.Lua.lora_set_appkey=function(a){return"lora.setAppKey("+(Blockly.Lua.valueToCode(a,"APPKEY",Blockly.Lua.ORDER_NONE)||"''")+")\n"};Blockly.Lua.lora_set_adr=function(a){var b="true";"0"==a.getFieldValue("ON_OFF")&&(b="false");return"lora.setAdr("+b+")\n"};Blockly.Lua.lora_set_dr=function(a){return"lora.setDr("+a.getFieldValue("DR")+")\n"};
Blockly.Lua.lora_set_retx=function(a){return"lora.setReTx("+a.getFieldValue("RETX")+")\n"};
Blockly.Lua.when_i_receive_a_lora_frame=function(a){var b=Blockly.Lua.statementToCodeNoIndent(a,"DO"),c="",d="";-1==codeSection.require.indexOf('require("block")')&&codeSection.require.push('require("block")');c+=Blockly.Lua.indent(0,"-- we need to wait for the completion of the board start")+"\n";c+=Blockly.Lua.indent(0,"_eventBoardStarted:wait()")+"\n\n";c+=Blockly.Lua.indent(0,"lora.whenReceived(function(port, payload)")+"\n";c+=Blockly.Lua.blockStart(1,a);""!=b&&(c+=Blockly.Lua.tryBlock(1,a,b));
c+=Blockly.Lua.blockEnd(1,a);c+=Blockly.Lua.indent(0,"end)")+"\n";d+=Blockly.Lua.indent(0,"-- when I receive a LoRa frame")+"\n";d+=Blockly.Lua.indent(0,"thread.start(function()")+"\n";d+=Blockly.Lua.tryBlock(1,a,c);return d+=Blockly.Lua.indent(0,"end)")+"\n"};
Blockly.Lua.lora_join=function(a){var b="";-1==codeSection.require.indexOf('require("block")')&&codeSection.require.push('require("block")');var c;c=""+(Blockly.Lua.indent(0,"if (_lora == nil) then")+"\n");c+=Blockly.Lua.indent(1,"_lora = true")+"\n";c+=Blockly.Lua.indent(1,"lora.attach(lora.BAND"+a.band+")")+"\n";c+=Blockly.Lua.indent(1,'lora.setAppEui("'+a.appeui+'")')+"\n";c+=Blockly.Lua.indent(1,'lora.setAppKey("'+a.appkey+'")')+"\n";c+=Blockly.Lua.indent(1,"lora.setDr("+a.dr+")")+"\n";c+=Blockly.Lua.indent(1,
"lora.setReTx("+a.retx+")")+"\n";c+=Blockly.Lua.indent(1,"\nif (os.flashEUI() == nil) then")+"\n";c+=Blockly.Lua.indent(2,'lora.setDevEui("'+a.deveui+'")')+"\n";c+=Blockly.Lua.indent(1,"end")+"\n\n";c+=Blockly.Lua.indent(0,"end")+"\n\n";c+=Blockly.Lua.blockStart(0,a);c+=Blockly.Lua.indent(0,"lora.join()")+"\n";c+=Blockly.Lua.blockEnd(0,a);b+=Blockly.Lua.indent(0,"-- lora join")+"\n";return b+=Blockly.Lua.tryBlock(0,a,c)+"\n"};
Blockly.Lua.lora_tx=function(a){var b=Blockly.Lua.valueToCode(a,"PAYLOAD",Blockly.Lua.ORDER_NONE)||"''",c=Blockly.Lua.valueToCode(a,"PORT",Blockly.Lua.ORDER_NONE),d=a.getFieldValue("CONF"),e="",d="0"==d?"false":"true";-1==codeSection.require.indexOf('require("block")')&&codeSection.require.push('require("block")');var f;f=""+Blockly.Lua.blockStart(0,a);f+=Blockly.Lua.indent(0,"-- setup LoRa WAN stack, if needed")+"\n";f+=Blockly.Lua.indent(0,"if (_lora == nil) then")+"\n";f+=Blockly.Lua.indent(1,
"_lora = true")+"\n";f+=Blockly.Lua.indent(1,"lora.attach(lora.BAND"+a.band+")")+"\n";"OTAA"==a.activation?(f+=Blockly.Lua.indent(1,"\nif (os.flashEUI() == nil) then")+"\n",f+=Blockly.Lua.indent(2,'lora.setDevEui("'+a.deveui+'")')+"\n",f+=Blockly.Lua.indent(1,"end")+"\n\n",f+=Blockly.Lua.indent(1,'lora.setAppEui("'+a.appeui+'")')+"\n",f+=Blockly.Lua.indent(1,'lora.setAppKey("'+a.appkey+'")')+"\n"):(f+=Blockly.Lua.indent(1,'lora.setDevAddr("'+a.devaddr+'")')+"\n",f+=Blockly.Lua.indent(1,'lora.setNwksKey("'+
a.nwkskey+'")')+"\n",f+=Blockly.Lua.indent(1,'lora.setAppsKey("'+a.appskey+'")')+"\n");f+=Blockly.Lua.indent(1,"lora.setDr("+a.dr+")")+"\n";f+=Blockly.Lua.indent(1,"lora.setAdr("+a.adr+")")+"\n";f+=Blockly.Lua.indent(1,"lora.setReTx("+a.retx+")")+"\n";f+=Blockly.Lua.indent(0,"end")+"\n\n";f+=Blockly.Lua.indent(0,"-- transmit")+"\n";f+=Blockly.Lua.indent(0,"lora.tx("+d+", "+c+", "+b+")")+"\n";f+=Blockly.Lua.blockEnd(0,a);e+=Blockly.Lua.indent(0,"-- lora tx")+"\n";return e+=Blockly.Lua.tryBlock(0,a,
f)+"\n"};Blockly.Lua.lora_start_gw=function(a){var b="",c;c=""+Blockly.Lua.blockStart(0,a);c+=Blockly.Lua.indent(0,"lora.attach(lora.BAND"+a.band+",lora.GATEWAY,nil,nil,"+a.freq+","+a.dr+")")+"\n";c+=Blockly.Lua.blockEnd(0,a);b+=Blockly.Lua.indent(0,"-- start lora gateway")+"\n";return b+=Blockly.Lua.indent(0,Blockly.Lua.tryBlock(0,a,c))+"\n"};
Blockly.Lua.lora_stop_gw=function(a){var b="",c;c=""+Blockly.Lua.blockStart(0,a);c+=Blockly.Lua.blockEnd(0,a);b+=Blockly.Lua.indent(0,"-- stop lora gateway")+"\n";return b+=Blockly.Lua.indent(0,Blockly.Lua.tryBlock(0,a,c))+"\n"};var codeSection=[],codeSectionBlock=[];codeSection.require=[];codeSection.events=[];codeSection.functions=[];codeSectionBlock.functions=[];codeSection.declaration=[];codeSection.start=[];codeSection.afterStart=[];codeSection["default"]=[];var codeSectionOrder=[];codeSectionOrder.push("require");
codeSectionOrder.push("events");codeSectionOrder.push("functions");codeSectionOrder.push("declaration");codeSectionOrder.push("default");codeSectionOrder.push("start");codeSectionOrder.push("afterStart");Blockly.Generator.prototype.INDENT="\t";Blockly.Generator.prototype.addCodeToSection=function(a,b,c){var d=!0;a=goog.string.trim(a);b=goog.string.trim(b);"functions"==a&&(d=-1==codeSectionBlock.functions.indexOf(c.type),codeSectionBlock.functions.push(c.type));d&&codeSection[a].push(b+"\n")};
Blockly.Generator.prototype.addDependency=function(a,b){a=goog.string.trim(a);""!=a&&"0"!=a&&-1==codeSection.require.indexOf('require("'+a+'")')&&codeSection.require.push('require("'+a+'")')};Blockly.Generator.prototype.postFormat=function(a,b){a=goog.string.trim(a);a+="\n";b.nextConnection&&b.nextConnection.isConnected()&&(a+="\n");return a};
Blockly.Generator.prototype.statementToCodeNoIndent=function(a,b){var c=a.getInputTargetBlock(b),d=this.blockToCode(c);goog.asserts.assertString(d,'Expecting code from statement block "%s".',c&&c.type);return d};
Blockly.Generator.prototype.workspaceToCode=function(a){a||(console.warn("No workspace specified in workspaceToCode call.  Guessing."),a=Blockly.getMainWorkspace());var b="default",c;for(c in codeSection)codeSection[c]=[];for(c in codeSectionBlock)codeSectionBlock[c]=[];var d=b=c=!1;this.init(a);for(var e=a.getAllBlocks(),f=0,g;g=e[f];f++)if(!g.disabled&&!g.getInheritedDisabled()){"when_board_starts"==g.type&&(c=!0);if("mqtt_publish"==g.type||"mqtt_subscribe"==g.type&&g.isInHatBlock())b=!0;if("wifi_start"==
g.type||"wifi_stop"==g.type&&g.isInHatBlock())d=!0}e=a.getTopBlocks(!0);a=""+(Blockly.Lua.indent(0,"-- this event is for sync the end of the board start with threads")+"\n");a+=Blockly.Lua.indent(0,"-- that must wait for this situation")+"\n";a+=Blockly.Lua.indent(0,"_eventBoardStarted = event.create()")+"\n\n";b&&(a+=Blockly.Lua.indent(0,"-- this lock is for protect the mqtt client connection")+"\n",a+=Blockly.Lua.indent(0,"_mqtt_lock = thread.createmutex()")+"\n\n");d&&(a+=Blockly.Lua.indent(0,
"-- network callback")+"\n",a+=Blockly.Lua.indent(0,"net.callback(function(event)")+"\n",a+=Blockly.Lua.indent(1,'if ((event.interface == "wf") and (event.type == "up")) then')+"\n",a+=Blockly.Lua.indent(2,"-- call user callbacks")+"\n",a+=Blockly.Lua.indent(2,"if (not (_network_callback_wifi_connected == nil)) then")+"\n",a+=Blockly.Lua.indent(3,"_network_callback_wifi_connected()")+"\n",a+=Blockly.Lua.indent(2,"end")+"\n",a+=Blockly.Lua.indent(1,'elseif ((event.interface == "wf") and (event.type == "down")) then')+
"\n",a+=Blockly.Lua.indent(2,"-- call user callbacks")+"\n",a+=Blockly.Lua.indent(2,"if (not (_network_callback_wifi_disconnected == nil)) then")+"\n",a+=Blockly.Lua.indent(3,"_network_callback_wifi_disconnected()")+"\n",a+=Blockly.Lua.indent(2,"end")+"\n",a+=Blockly.Lua.indent(1,"end")+"\n",a+=Blockly.Lua.indent(0,"end)")+"\n");codeSection.events.push(a);for(f=0;g=e[f];f++)g.isHatBlock()&&(b="default","undefined"!==typeof g.section&&(b=g.section()),a=this.blockToCode(g),goog.isArray(a)&&(a=a[0]),
a&&(g.outputConnection&&this.scrubNakedValue&&(a=this.scrubNakedValue(a)),codeSection[b].push(a)));c||(a=Blockly.Lua.indent(0,"thread.start(function()")+"\n",a+=Blockly.Lua.indent(1,"-- board is started")+"\n",a+=Blockly.Lua.indent(1,"_eventBoardStarted:broadcast(false)")+"\n",a+=Blockly.Lua.indent(0,"end)")+"\n",codeSection.start.push(a));for(var k in Blockly.Lua.definitions_)codeSection.declaration.push(Blockly.Lua.definitions_[k]);delete Blockly.Lua.definitions_;delete Blockly.Lua.functionNames_;
Blockly.Lua.variableDB_.reset();var h="",l="";codeSectionOrder.forEach(function(a,b){""!=codeSection[a]&&(l=codeSection[a].join("\n"),h+=l+"\n","require"==a&&(h+="\n"))});h=h.replace(/^\s+\n/,"");h=h.replace(/\n\s+$/,"\n");return h=h.replace(/[ \t]+\n/g,"\n")};
Blockly.Generator.prototype.usesMQTT=function(a){a||(console.warn("No workspace specified in workspaceToCode call.  Guessing."),a=Blockly.getMainWorkspace());a=a.getAllBlocks();for(var b=0,c;c=a[b];b++)if("mqtt_publish"==c.type||"mqtt_subscribe"==c.type)return!0;return!1};
Blockly.Generator.prototype.oneBlockToCode=function(a){if(!a)return"";if(a.disabled)return this.blockToCode(a.getNextBlock());var b=this[a.type];goog.asserts.assertFunction(b,'Language "%s" does not know how to generate code for block type "%s".',this.name_,a.type);b=b.call(a,a);if(goog.isArray(b))return goog.asserts.assert(a.outputConnection,'Expecting string from statement block "%s".',a.type),[this.scrub_(a,b[0]),b[1]];if(goog.isString(b))return a=a.id.replace(/\$/g,"$$$$"),this.STATEMENT_PREFIX&&
(b=this.STATEMENT_PREFIX.replace(/%1/g,"'"+a+"'")+b),b;if(null===b)return"";goog.asserts.fail("Invalid code generated: %s",b)};
Blockly.Generator.prototype.blockWatcherCode=function(a){var b=[],c;this.init(a.workspace);for(c in codeSection)codeSection[c]=[];codeSection.require.push('require("block")');a=this.oneBlockToCode(a);codeSectionOrder.forEach(function(a,c){"default"!=a&&""!=codeSection[a]&&(b+=codeSection[a].join("\n")+"\n")});b+="function _code()\n";b+="local previous = wcBlock.developerMode\n";b+="wcBlock.developerMode = false\n";b=goog.isArray(a)?b+("print("+a[0]+")\n"):b+("print("+a+")\n");b+="wcBlock.developerMode = previous\n";
return b+="end"};
Blockly.Generator.prototype.blockCode=function(a){var b=[],c;this.init(a.workspace);for(c in codeSection)codeSection[c]=[];codeSection.require.push('require("block")');a=this.oneBlockToCode(a);codeSectionOrder.forEach(function(a,c){"default"!=a&&""!=codeSection[a]&&(b+=codeSection[a].join("\n")+"\n")});b+="function _code()\n";b+="thread.start(function()\n";b+="local previous = wcBlock.developerMode\n";b+="wcBlock.developerMode = false\n";b=goog.isArray(a)?b+(a[0]+"\n"):b+(a+"\n");b+="wcBlock.developerMode = previous\n";
b+="end)\n";return b+="end"};"use strict";Blockly.Lua.math={};Blockly.Lua.math_number=function(a){a=parseFloat(a.getFieldValue("NUM"));return[a,0>a?Blockly.Lua.ORDER_UNARY:Blockly.Lua.ORDER_ATOMIC]};
Blockly.Lua.math_arithmetic=function(a){var b={ADD:[" + ",Blockly.Lua.ORDER_ADDITIVE],MINUS:[" - ",Blockly.Lua.ORDER_ADDITIVE],MULTIPLY:[" * ",Blockly.Lua.ORDER_MULTIPLICATIVE],DIVIDE:[" / ",Blockly.Lua.ORDER_MULTIPLICATIVE],POWER:[" ^ ",Blockly.Lua.ORDER_EXPONENTIATION]}[a.getFieldValue("OP")],c=b[0],b=b[1],d=Blockly.Lua.valueToCode(a,"A",b)||"0";a=Blockly.Lua.valueToCode(a,"B",b)||"0";return[d+c+a,b]};
Blockly.Lua.math_single=function(a){var b=a.getFieldValue("OP");if("NEG"==b)return a=Blockly.Lua.valueToCode(a,"NUM",Blockly.Lua.ORDER_UNARY)||"0",["-"+a,Blockly.Lua.ORDER_UNARY];a="SIN"==b||"COS"==b||"TAN"==b?Blockly.Lua.valueToCode(a,"NUM",Blockly.Lua.ORDER_MULTIPLICATIVE)||"0":Blockly.Lua.valueToCode(a,"NUM",Blockly.Lua.ORDER_NONE)||"0";switch(b){case "ABS":b="math.abs("+a+")";break;case "ROOT":b="math.sqrt("+a+")";break;case "LN":b="math.log("+a+")";break;case "LOG10":b="math.log("+a+", 10)";
break;case "EXP":b="math.exp("+a+")";break;case "POW10":b="10 ^ "+a;break;case "ROUND":b="math.floor("+a+" + .5)";break;case "ROUNDUP":b="math.ceil("+a+")";break;case "ROUNDDOWN":b="math.floor("+a+")";break;case "SIN":b="math.sin(math.rad("+a+"))";break;case "COS":b="math.cos(math.rad("+a+"))";break;case "TAN":b="math.tan(math.rad("+a+"))";break;case "ASIN":b="math.deg(math.asin("+a+"))";break;case "ACOS":b="math.deg(math.acos("+a+"))";break;case "ATAN":b="math.deg(math.atan("+a+"))";break;default:throw"Unknown math operator: "+
b;}return[b,Blockly.Lua.ORDER_HIGH]};Blockly.Lua.math_constant=function(a){return{PI:["math.pi",Blockly.Lua.ORDER_HIGH],E:["math.exp(1)",Blockly.Lua.ORDER_HIGH],GOLDEN_RATIO:["(1 + math.sqrt(5)) / 2",Blockly.Lua.ORDER_MULTIPLICATIVE],SQRT2:["math.sqrt(2)",Blockly.Lua.ORDER_HIGH],SQRT1_2:["math.sqrt(1 / 2)",Blockly.Lua.ORDER_HIGH],INFINITY:["math.huge",Blockly.Lua.ORDER_HIGH]}[a.getFieldValue("CONSTANT")]};
Blockly.Lua.math_number_property=function(a){var b=Blockly.Lua.valueToCode(a,"NUMBER_TO_CHECK",Blockly.Lua.ORDER_MULTIPLICATIVE)||"0",c=a.getFieldValue("PROPERTY"),d;if("PRIME"==c)return[Blockly.Lua.provideFunction_("math_isPrime",["function "+Blockly.Lua.FUNCTION_NAME_PLACEHOLDER_+"(n)","  -- https://en.wikipedia.org/wiki/Primality_test#Naive_methods","  if n == 2 or n == 3 then","    return true","  end","  -- False if n is NaN, negative, is 1, or not whole.","  -- And false if n is divisible by 2 or 3.",
"  if not(n > 1) or n % 1 ~= 0 or n % 2 == 0 or n % 3 == 0 then","    return false","  end","  -- Check all the numbers of form 6k +/- 1, up to sqrt(n).","  for x = 6, math.sqrt(n) + 1.5, 6 do","    if n % (x - 1) == 0 or n % (x + 1) == 0 then","      return false","    end","  end","  return true","end"])+"("+b+")",Blockly.Lua.ORDER_HIGH];switch(c){case "EVEN":d=b+" % 2 == 0";break;case "ODD":d=b+" % 2 == 1";break;case "WHOLE":d=b+" % 1 == 0";break;case "POSITIVE":d=b+" > 0";break;case "NEGATIVE":d=
b+" < 0";break;case "DIVISIBLE_BY":a=Blockly.Lua.valueToCode(a,"DIVISOR",Blockly.Lua.ORDER_MULTIPLICATIVE);if(!a||"0"==a)return["nil",Blockly.Lua.ORDER_ATOMIC];d=b+" % "+a+" == 0"}return[d,Blockly.Lua.ORDER_RELATIONAL]};Blockly.Lua.math_change=function(a){var b=Blockly.Lua.valueToCode(a,"DELTA",Blockly.Lua.ORDER_ADDITIVE)||"0";a=Blockly.Lua.variableDB_.getName(a.getFieldValue("VAR"),Blockly.Variables.NAME_TYPE);return a+" = "+a+" + "+b+"\n"};Blockly.Lua.math_round=Blockly.Lua.math_single;
Blockly.Lua.math_trig=Blockly.Lua.math_single;
Blockly.Lua.math_on_list=function(a){function b(){return Blockly.Lua.provideFunction_("math_sum",["function "+Blockly.Lua.FUNCTION_NAME_PLACEHOLDER_+"(t)","  local result = 0","  for _, v in ipairs(t) do","    result = result + v","  end","  return result","end"])}var c=a.getFieldValue("OP");a=Blockly.Lua.valueToCode(a,"LIST",Blockly.Lua.ORDER_NONE)||"{}";switch(c){case "SUM":c=b();break;case "MIN":c=Blockly.Lua.provideFunction_("math_min",["function "+Blockly.Lua.FUNCTION_NAME_PLACEHOLDER_+"(t)",
"  if #t == 0 then","    return 0","  end","  local result = math.huge","  for _, v in ipairs(t) do","    if v < result then","      result = v","    end","  end","  return result","end"]);break;case "AVERAGE":c=Blockly.Lua.provideFunction_("math_average",["function "+Blockly.Lua.FUNCTION_NAME_PLACEHOLDER_+"(t)","  if #t == 0 then","    return 0","  end","  return "+b()+"(t) / #t","end"]);break;case "MAX":c=Blockly.Lua.provideFunction_("math_max",["function "+Blockly.Lua.FUNCTION_NAME_PLACEHOLDER_+
"(t)","  if #t == 0 then","    return 0","  end","  local result = -math.huge","  for _, v in ipairs(t) do","    if v > result then","      result = v","    end","  end","  return result","end"]);break;case "MEDIAN":c=Blockly.Lua.provideFunction_("math_median",["function "+Blockly.Lua.FUNCTION_NAME_PLACEHOLDER_+"(t)","  -- Source: http://lua-users.org/wiki/SimpleStats","  if #t == 0 then","    return 0","  end","  local temp={}","  for _, v in ipairs(t) do",'    if type(v) == "number" then',"      table.insert(temp, v)",
"    end","  end","  table.sort(temp)","  if #temp % 2 == 0 then","    return (temp[#temp/2] + temp[(#temp/2)+1]) / 2","  else","    return temp[math.ceil(#temp/2)]","  end","end"]);break;case "MODE":c=Blockly.Lua.provideFunction_("math_modes",["function "+Blockly.Lua.FUNCTION_NAME_PLACEHOLDER_+"(t)","  -- Source: http://lua-users.org/wiki/SimpleStats","  local counts={}","  for _, v in ipairs(t) do","    if counts[v] == nil then","      counts[v] = 1","    else","      counts[v] = counts[v] + 1",
"    end","  end","  local biggestCount = 0","  for _, v  in pairs(counts) do","    if v > biggestCount then","      biggestCount = v","    end","  end","  local temp={}","  for k, v in pairs(counts) do","    if v == biggestCount then","      table.insert(temp, k)","    end","  end","  return temp","end"]);break;case "STD_DEV":c=Blockly.Lua.provideFunction_("math_standard_deviation",["function "+Blockly.Lua.FUNCTION_NAME_PLACEHOLDER_+"(t)","  local m","  local vm","  local total = 0","  local count = 0",
"  local result","  m = #t == 0 and 0 or "+b()+"(t) / #t","  for _, v in ipairs(t) do","    if type(v) == 'number' then","      vm = v - m","      total = total + (vm * vm)","      count = count + 1","    end","  end","  result = math.sqrt(total / (count-1))","  return result","end"]);break;case "RANDOM":c=Blockly.Lua.provideFunction_("math_random_list",["function "+Blockly.Lua.FUNCTION_NAME_PLACEHOLDER_+"(t)","  if #t == 0 then","    return nil","  end","  return t[math.random(#t)]","end"]);break;
default:throw"Unknown operator: "+c;}return[c+"("+a+")",Blockly.Lua.ORDER_HIGH]};Blockly.Lua.math_modulo=function(a){var b=Blockly.Lua.valueToCode(a,"DIVIDEND",Blockly.Lua.ORDER_MULTIPLICATIVE)||"0";a=Blockly.Lua.valueToCode(a,"DIVISOR",Blockly.Lua.ORDER_MULTIPLICATIVE)||"0";return[b+" % "+a,Blockly.Lua.ORDER_MULTIPLICATIVE]};
Blockly.Lua.math_constrain=function(a){var b=Blockly.Lua.valueToCode(a,"VALUE",Blockly.Lua.ORDER_NONE)||"0",c=Blockly.Lua.valueToCode(a,"LOW",Blockly.Lua.ORDER_NONE)||"-math.huge";a=Blockly.Lua.valueToCode(a,"HIGH",Blockly.Lua.ORDER_NONE)||"math.huge";return["math.min(math.max("+b+", "+c+"), "+a+")",Blockly.Lua.ORDER_HIGH]};
Blockly.Lua.math_random_int=function(a){var b=Blockly.Lua.valueToCode(a,"FROM",Blockly.Lua.ORDER_NONE)||"0";a=Blockly.Lua.valueToCode(a,"TO",Blockly.Lua.ORDER_NONE)||"0";return["math.random("+b+", "+a+")",Blockly.Lua.ORDER_HIGH]};Blockly.Lua.math_random_float=function(a){return["math.random()",Blockly.Lua.ORDER_HIGH]};"use strict";Blockly.Lua.MQTT={};Blockly.Lua.MQTT.helper={};
Blockly.Lua.mqtt_publish=function(a){var b=Blockly.Lua.valueToCode(a,"TOPIC",Blockly.Lua.ORDER_NONE)||"''",c=Blockly.Lua.valueToCode(a,"PAYLOAD",Blockly.Lua.ORDER_NONE)||"''",d=a.getFieldValue("QOS"),e="";-1==codeSection.require.indexOf('require("block")')&&codeSection.require.push('require("block")');var f;f=""+(Blockly.Lua.indent(0,"-- create the MQTT client and connect, if needed")+"\n");f+=Blockly.Lua.indent(0,"_mqtt_lock:lock()")+"\n";f+=Blockly.Lua.indent(0,"if (_mqtt == nil) then")+"\n";f+=
Blockly.Lua.indent(1,'_mqtt = mqtt.client("'+a.clientid+'", "'+a.host+'", '+a.port+", false, nil, "+(0<d?"true":"false")+")")+"\n";f+=Blockly.Lua.indent(1,'_mqtt:connect("'+a.username+'","'+a.password+'")')+"\n";f+=Blockly.Lua.indent(0,"end")+"\n";f+=Blockly.Lua.indent(0,"_mqtt_lock:unlock()")+"\n\n";f+=Blockly.Lua.indent(0,"-- publish to topic")+"\n";f+=Blockly.Lua.indent(0,"_mqtt:publish("+b+", "+c+", mqtt.QOS"+d+")")+"\n";f+=Blockly.Lua.blockEnd(0,a);e+=Blockly.Lua.indent(0,"-- publish to MQTT topic "+
b)+"\n";return e+=Blockly.Lua.tryBlock(0,a,f)+"\n"};
Blockly.Lua.mqtt_subscribe=function(a){var b=Blockly.Lua.valueToCode(a,"TOPIC",Blockly.Lua.ORDER_NONE)||"''",c=Blockly.Lua.statementToCodeNoIndent(a,"DO"),d=a.getFieldValue("QOS"),e="";-1==codeSection.require.indexOf('require("block")')&&codeSection.require.push('require("block")');var f;f=""+(Blockly.Lua.indent(0,"-- create the MQTT client and connect, if needed")+"\n");f+=Blockly.Lua.indent(0,"_mqtt_lock:lock()")+"\n";f+=Blockly.Lua.indent(0,"if (_mqtt == nil) then")+"\n";f+=Blockly.Lua.indent(1,
'_mqtt = mqtt.client("'+a.clientid+'", "'+a.host+'", '+a.port+", false, nil, "+(0<d?"true":"false")+")")+"\n";f+=Blockly.Lua.indent(1,'_mqtt:connect("'+a.username+'","'+a.password+'")')+"\n";f+=Blockly.Lua.indent(0,"end")+"\n";f+=Blockly.Lua.indent(0,"_mqtt_lock:unlock()")+"\n\n";f+=Blockly.Lua.indent(0,"-- subscribe to topic")+"\n";f+=Blockly.Lua.indent(0,"_mqtt:subscribe("+b+", mqtt.QOS"+d+", function(length, payload)")+"\n";f+=Blockly.Lua.indent(1,"-- a new message is available in length / payload arguments")+
"\n";f+=Blockly.Lua.blockStart(1,a);""!=c&&(f+=Blockly.Lua.tryBlock(1,a,c));f+=Blockly.Lua.blockEnd(1,a);f+=Blockly.Lua.indent(0,"end)")+"\n";e+=Blockly.Lua.indent(0,"-- subscribe to MQTT topic "+b)+"\n";e+=Blockly.Lua.indent(0,"thread.start(function()")+"\n";e+=Blockly.Lua.indent(1,"_eventBoardStarted:wait()")+"\n\n";e+=Blockly.Lua.tryBlock(1,a,f);return e+=Blockly.Lua.indent(0,"end)")+"\n"};"use strict";Blockly.Lua.procedures={};
Blockly.Lua.procedures_defreturn=function(a){var b=Blockly.Lua.variableDB_.getName(a.getFieldValue("NAME"),Blockly.Procedures.NAME_TYPE),c=Blockly.Lua.statementToCode(a,"STACK");Blockly.Lua.STATEMENT_PREFIX&&(c=Blockly.Lua.prefixLines(Blockly.Lua.STATEMENT_PREFIX.replace(/%1/g,"'"+a.id+"'"),Blockly.Lua.INDENT)+c);Blockly.Lua.INFINITE_LOOP_TRAP&&(c=Blockly.Lua.INFINITE_LOOP_TRAP.replace(/%1/g,"'"+a.id+"'")+c);var d=Blockly.Lua.valueToCode(a,"RETURN",Blockly.Lua.ORDER_NONE)||"";d?d="  return "+d+"\n":
c||(c="");for(var e=[],f=0;f<a.arguments_.length;f++)e[f]=Blockly.Lua.variableDB_.getName(a.arguments_[f],Blockly.Variables.NAME_TYPE);c="function "+b+"("+e.join(", ")+")\n"+c+d+"end\n";c=Blockly.Lua.scrub_(a,c);Blockly.Lua.definitions_["%"+b]=c;return null};Blockly.Lua.procedures_defnoreturn=Blockly.Lua.procedures_defreturn;
Blockly.Lua.procedures_callreturn=function(a){for(var b=Blockly.Lua.variableDB_.getName(a.getFieldValue("NAME"),Blockly.Procedures.NAME_TYPE),c=[],d=0;d<a.arguments_.length;d++)c[d]=Blockly.Lua.valueToCode(a,"ARG"+d,Blockly.Lua.ORDER_NONE)||"nil";return[b+"("+c.join(", ")+")",Blockly.Lua.ORDER_HIGH]};
Blockly.Lua.procedures_callnoreturn=function(a){for(var b=Blockly.Lua.variableDB_.getName(a.getFieldValue("NAME"),Blockly.Procedures.NAME_TYPE),c=[],d=0;d<a.arguments_.length;d++)c[d]=Blockly.Lua.valueToCode(a,"ARG"+d,Blockly.Lua.ORDER_NONE)||"nil";return b+"("+c.join(", ")+")\n"};
Blockly.Lua.procedures_ifreturn=function(a){var b="if "+(Blockly.Lua.valueToCode(a,"CONDITION",Blockly.Lua.ORDER_NONE)||"false")+" then\n";a.hasReturnValue_?(a=Blockly.Lua.valueToCode(a,"VALUE",Blockly.Lua.ORDER_NONE)||"nil",b+="  return "+a+"\n"):b+="  return\n";return b+"end\n"};"use strict";Blockly.Lua.sensors={};
Blockly.Lua.sensors.helper={getInterface:function(a){for(var b="",c=a["interface"].split(","),d=0;d<c.length;d++)"GPIO"==c[d]?(""!=b&&(b+=", "),b+="pio."+Code.status.maps.digitalPins[a["interface"+d+"_unit"]][0]):"ADC"==c[d]?1==a["interface"+d+"_unit"]?(""!=b&&(b+=", "),b+="adc.ADC1, pio."+Code.status.maps.analogPins[a["interface"+d+"_subunit"]][0]):(""!=b&&(b+=", "),b+="adc."+Code.status.maps.externalAdcUnits[a["interface"+d+"_unit"]][0]+", "+a["interface"+d+"_subunit"]):"I2C"==c[d]?(""!=b&&(b+=
", "),b+="i2c."+Code.status.maps.i2cUnits[a["interface"+d+"_unit"]][1]+", 0"):"UART"==c[d]?(""!=b&&(b+=", "),b+="uart."+Code.status.maps.uartUnits[a["interface"+d+"_unit"]][1]):"1-WIRE"==c[d]&&(""!=b&&(b+=", "),b+="pio."+Code.status.maps.digitalPins[a["interface"+d+"_unit"]][0]+", "+a["interface"+d+"_device"]);return b},nameSensor:function(a){return a.sid.replace(/\s|-/g,"_")},attach:function(a){var b="",c=Blockly.Lua.sensors.helper.getInterface(a),b=b+(Blockly.Lua.indent(0,"if (_"+a.name+"_"+Blockly.Lua.sensors.helper.nameSensor(a)+
" == nil) then")+"\n"),b=b+(Blockly.Lua.indent(1,"_"+a.name+"_"+Blockly.Lua.sensors.helper.nameSensor(a)+' = sensor.attach("'+a.sid+'"'+(""!=c?", ":"")+c+")")+"\n");return b+=Blockly.Lua.indent(0,"end")+"\n\n"}};
Blockly.Lua.sensor_read=function(a){var b=a.getFieldValue("PROVIDES");-1==codeSection.require.indexOf('require("block")')&&codeSection.require.push('require("block")');var c;c=""+(Blockly.Lua.indent(0,"function _get"+a.name+"_"+b.replace(/\s|-/g,"_")+"()")+"\n");var d;d=""+Blockly.Lua.sensors.helper.attach(a);d+=Blockly.Lua.indent(0,"value = _"+a.name+"_"+Blockly.Lua.sensors.helper.nameSensor(a)+':read("'+b+'")')+"\n";c+=Blockly.Lua.indent(1,"local value\n")+"\n";c+=Blockly.Lua.indent(0,Blockly.Lua.tryBlock(1,
a,d))+"\n";c+=Blockly.Lua.indent(1,"return value\n");c+=Blockly.Lua.indent(0,"end\n");codeSection.declaration.push(c);return["_get"+a.name+"_"+b.replace(/\s|-/g,"_")+"()",Blockly.Lua.ORDER_HIGH]};
Blockly.Lua.sensor_set=function(a){var b=a.getFieldValue("PROPERTIES"),c=Blockly.Lua.valueToCode(a,"VALUE",Blockly.Lua.ORDER_NONE),d="";-1==codeSection.require.indexOf('require("block")')&&codeSection.require.push('require("block")');var e;e=""+(Blockly.Lua.indent(1,'local instance = "_'+a.name+"_"+Blockly.Lua.sensors.helper.nameSensor(a)+'"')+"\n\n");e+=Blockly.Lua.sensors.helper.attach(a);e+=Blockly.Lua.indent(1,"_"+a.name+"_"+Blockly.Lua.sensors.helper.nameSensor(a)+':set("'+b+'", '+c+")")+"\n";
return d+=Blockly.Lua.indent(0,Blockly.Lua.tryBlock(0,a,e))+"\n"};
Blockly.Lua.sensor_when=function(a){var b=a.getFieldValue("PROVIDES"),c=Blockly.Lua.statementToCodeNoIndent(a,"DO"),d="";-1==codeSection.require.indexOf('require("block")')&&codeSection.require.push('require("block")');var e;e=""+(Blockly.Lua.indent(0,"-- we need to wait for the completion of the board start")+"\n");e+=Blockly.Lua.indent(0,"_eventBoardStarted:wait()")+"\n\n";e+=Blockly.Lua.indent(0,Blockly.Lua.sensors.helper.attach(a));e+=Blockly.Lua.indent(0,"_"+a.name+"_"+Blockly.Lua.sensors.helper.nameSensor(a)+
":callback(function(magnitude)")+"\n";e+=Blockly.Lua.indent(1,"local value = magnitude."+b)+"\n\n";e+=Blockly.Lua.indent(1,"if value == nil then return end")+"\n\n";e+=Blockly.Lua.blockStart(2,a);""!=c&&(e+=Blockly.Lua.indent(2,c));e+=Blockly.Lua.blockEnd(2,a);e+=Blockly.Lua.indent(1,"end)")+"\n";d+=Blockly.Lua.indent(0,"thread.start(function()")+"\n";d+=Blockly.Lua.tryBlock(1,a,e);return d+=Blockly.Lua.indent(0,"end)")+"\n"};"use strict";Blockly.Lua.servo={};
Blockly.Lua.servo.helper={isServo:function(a,b){return"servo_move"==b.type&&a.getFieldValue("PIN")==b.getFieldValue("PIN")},hasAncestors:function(a){for(var b=a.previousConnection;b;)if(b=b.targetBlock()){if(Blockly.Lua.servo.helper.isServo(a,b))return!0;b=b.previousConnection}return!1},instance:function(a){return"_servo_"+Blockly.Lua.io.helper.nameDigital(a)},attach:function(a){var b="";Blockly.Lua.servo.helper.hasAncestors(a)||(b+=Blockly.Lua.indent(0,"if ("+Blockly.Lua.servo.helper.instance(a)+
" == nil) then")+"\n",b+=Blockly.Lua.indent(1,Blockly.Lua.servo.helper.instance(a)+" = servo.attach("+Blockly.Lua.io.helper.nameDigital(a)+")")+"\n",b+=Blockly.Lua.indent(0,"end")+"\n\n");return b}};
Blockly.Lua.servo_move=function(a){a.getFieldValue("PIN");var b=Blockly.Lua.valueToCode(a,"VALUE",Blockly.Lua.ORDER_NONE)||"''",c="",d="",e;e=""+(Blockly.Lua.indent(0,"-- servos")+"\n");e+=Blockly.Lua.indent(0,"_servo_pio = {}")+"\n";Blockly.Lua.addCodeToSection("declaration",e,a);Blockly.Lua.require("block");d+=Blockly.Lua.servo.helper.attach(a);d+=Blockly.Lua.indent(0,Blockly.Lua.servo.helper.instance(a)+":write("+b+")")+"\n";return c+=Blockly.Lua.tryBlock(0,a,d,"move servo at pin "+Blockly.Lua.io.helper.nameDigital(a)+
" by "+b)};"use strict";Blockly.Lua.texts={};Blockly.Lua.text=function(a){return[Blockly.Lua.quote_(a.getFieldValue("TEXT")),Blockly.Lua.ORDER_ATOMIC]};
Blockly.Lua.text_join=function(a){if(0==a.itemCount_)return["''",Blockly.Lua.ORDER_ATOMIC];if(1==a.itemCount_)return["tostring("+(Blockly.Lua.valueToCode(a,"ADD0",Blockly.Lua.ORDER_NONE)||"''")+")",Blockly.Lua.ORDER_HIGH];if(2==a.itemCount_){var b=Blockly.Lua.valueToCode(a,"ADD0",Blockly.Lua.ORDER_CONCATENATION)||"''";a=Blockly.Lua.valueToCode(a,"ADD1",Blockly.Lua.ORDER_CONCATENATION)||"''";return[b+" .. "+a,Blockly.Lua.ORDER_CONCATENATION]}for(var b=[],c=0;c<a.itemCount_;c++)b[c]=Blockly.Lua.valueToCode(a,
"ADD"+c,Blockly.Lua.ORDER_NONE)||"''";a="table.concat({"+b.join(", ")+"})";return[a,Blockly.Lua.ORDER_HIGH]};Blockly.Lua.text_append=function(a){var b=Blockly.Lua.variableDB_.getName(a.getFieldValue("VAR"),Blockly.Variables.NAME_TYPE);a=Blockly.Lua.valueToCode(a,"TEXT",Blockly.Lua.ORDER_CONCATENATION)||"''";return b+" = "+b+" .. "+a+"\n"};Blockly.Lua.text_length=function(a){return["#"+(Blockly.Lua.valueToCode(a,"VALUE",Blockly.Lua.ORDER_UNARY)||"''"),Blockly.Lua.ORDER_UNARY]};
Blockly.Lua.text_isEmpty=function(a){return["#"+(Blockly.Lua.valueToCode(a,"VALUE",Blockly.Lua.ORDER_UNARY)||"''")+" == 0",Blockly.Lua.ORDER_RELATIONAL]};
Blockly.Lua.text_indexOf=function(a){var b=Blockly.Lua.valueToCode(a,"FIND",Blockly.Lua.ORDER_NONE)||"''",c=Blockly.Lua.valueToCode(a,"VALUE",Blockly.Lua.ORDER_NONE)||"''";return[("FIRST"==a.getFieldValue("END")?Blockly.Lua.provideFunction_("firstIndexOf",["function "+Blockly.Lua.FUNCTION_NAME_PLACEHOLDER_+"(str, substr) ","  local i = string.find(str, substr, 1, true)","  if i == nil then","    return 0","  else","    return i","  end","end"]):Blockly.Lua.provideFunction_("lastIndexOf",["function "+
Blockly.Lua.FUNCTION_NAME_PLACEHOLDER_+"(str, substr)","  local i = string.find(string.reverse(str), string.reverse(substr), 1, true)","  if i then","    return #str + 2 - i - #substr","  end","  return 0","end"]))+"("+c+", "+b+")",Blockly.Lua.ORDER_HIGH]};
Blockly.Lua.text_charAt=function(a){var b=a.getFieldValue("WHERE")||"FROM_START",c=Blockly.Lua.valueToCode(a,"AT","FROM_END"==b?Blockly.Lua.ORDER_UNARY:Blockly.Lua.ORDER_NONE)||"1";a=Blockly.Lua.valueToCode(a,"VALUE",Blockly.Lua.ORDER_NONE)||"''";if("RANDOM"==b)b=Blockly.Lua.provideFunction_("text_random_letter",["function "+Blockly.Lua.FUNCTION_NAME_PLACEHOLDER_+"(str)","  local index = math.random(string.len(str))","  return string.sub(str, index, index)","end"]),a=b+"("+a+")";else{if("FIRST"==
b)c="1";else if("LAST"==b)c="-1";else if("FROM_START"!=b)if("FROM_END"==b)c="-"+c;else throw"Unhandled option (text_charAt).";c.match(/^-?\w*$/)?a="string.sub("+a+", "+c+", "+c+")":(b=Blockly.Lua.provideFunction_("text_char_at",["function "+Blockly.Lua.FUNCTION_NAME_PLACEHOLDER_+"(str, index)","  return string.sub(str, index, index)","end"]),a=b+"("+a+", "+c+")")}return[a,Blockly.Lua.ORDER_HIGH]};
Blockly.Lua.text_getSubstring=function(a){var b=Blockly.Lua.valueToCode(a,"STRING",Blockly.Lua.ORDER_NONE)||"''",c=a.getFieldValue("WHERE1"),d=Blockly.Lua.valueToCode(a,"AT1","FROM_END"==c?Blockly.Lua.ORDER_UNARY:Blockly.Lua.ORDER_NONE)||"1";if("FIRST"==c)c=1;else if("FROM_START"==c)c=d;else if("FROM_END"==c)c="-"+d;else throw"Unhandled option (text_getSubstring)";d=a.getFieldValue("WHERE2");a=Blockly.Lua.valueToCode(a,"AT2","FROM_END"==d?Blockly.Lua.ORDER_UNARY:Blockly.Lua.ORDER_NONE)||"1";if("LAST"==
d)a=-1;else if("FROM_START"!=d)if("FROM_END"==d)a="-"+a;else throw"Unhandled option (text_getSubstring)";return["string.sub("+b+", "+c+", "+a+")",Blockly.Lua.ORDER_HIGH]};
Blockly.Lua.text_changeCase=function(a){var b=a.getFieldValue("CASE");a=Blockly.Lua.valueToCode(a,"TEXT",Blockly.Lua.ORDER_NONE)||"''";if("UPPERCASE"==b)var c="string.upper";else"LOWERCASE"==b?c="string.lower":"TITLECASE"==b&&(c=Blockly.Lua.provideFunction_("text_titlecase",["function "+Blockly.Lua.FUNCTION_NAME_PLACEHOLDER_+"(str)","  local buf = {}","  local inWord = false","  for i = 1, #str do","    local c = string.sub(str, i, i)","    if inWord then","      table.insert(buf, string.lower(c))",
'      if string.find(c, "%s") then',"        inWord = false","      end","    else","      table.insert(buf, string.upper(c))","      inWord = true","    end","  end","  return table.concat(buf)","end"]));return[c+"("+a+")",Blockly.Lua.ORDER_HIGH]};Blockly.Lua.text_trim=function(a){var b={LEFT:"^%s*(,-)",RIGHT:"(.-)%s*$",BOTH:"^%s*(.-)%s*$"}[a.getFieldValue("MODE")];return["string.gsub("+(Blockly.Lua.valueToCode(a,"TEXT",Blockly.Lua.ORDER_NONE)||"''")+', "'+b+'", "%1")',Blockly.Lua.ORDER_HIGH]};
Blockly.Lua.text_print=function(a){return"print("+(Blockly.Lua.valueToCode(a,"TEXT",Blockly.Lua.ORDER_NONE)||"''")+")\n"};
Blockly.Lua.text_prompt_ext=function(a){var b=a.getField("TEXT")?Blockly.Lua.quote_(a.getFieldValue("TEXT")):Blockly.Lua.valueToCode(a,"TEXT",Blockly.Lua.ORDER_NONE)||"''",b=Blockly.Lua.provideFunction_("text_prompt",["function "+Blockly.Lua.FUNCTION_NAME_PLACEHOLDER_+"(msg)","  io.write(msg)","  io.flush()","  return io.read()","end"])+"("+b+")";"NUMBER"==a.getFieldValue("TYPE")&&(b="tonumber("+b+", 10)");return[b,Blockly.Lua.ORDER_HIGH]};Blockly.Lua.text_prompt=Blockly.Lua.text_prompt_ext;"use strict";
Blockly.Lua.textadds={};Blockly.Lua.text_pack=function(a){Blockly.Lua.valueToCode(a,"TO0",Blockly.Lua.ORDER_NONE);for(var b=[],c=0;c<a.withCount_;c++)b[c]=Blockly.Lua.valueToCode(a,"WITH"+c,Blockly.Lua.ORDER_NONE)||"''";return["pack.pack("+b.join(", ")+")",Blockly.Lua.ORDER_HIGH]};
Blockly.Lua.text_unpack=function(a){for(var b=Blockly.Lua.valueToCode(a,"FROM0",Blockly.Lua.ORDER_NONE),c="",d=0;d<a.toCount_;d++)c+=Blockly.Lua.valueToCode(a,"TO"+d,Blockly.Lua.ORDER_NONE)+", "+b+" = pack.unpack("+b+", true)\n";return c};"use strict";Blockly.Lua.threads={};Blockly.Lua.thread_start=function(a){var b=Blockly.Lua.valueToCode(a,"THID",Blockly.Lua.ORDER_NONE);a=Blockly.Lua.statementToCode(a,"DO");""!=b&&(b+=" = ");return b+"thread.start(function()\r\n"+a+"end)\r\n"};
Blockly.Lua.thread_create=function(a){var b=Blockly.Lua.valueToCode(a,"THID",Blockly.Lua.ORDER_NONE);a=Blockly.Lua.statementToCode(a,"DO");""!=b&&(b+=" = ");return b+"thread.create(function()\r\n"+a+"end)\r\n"};Blockly.Lua.thread_stop=function(a){a=a.getFieldValue("THID");"all"==a&&(a="");return"thread.stop("+a+")\r\n"};Blockly.Lua.thread_resume=function(a){a=a.getFieldValue("THID");"all"==a&&(a="");return"thread.resume("+a+")\r\n"};
Blockly.Lua.thread_suspend=function(a){a=a.getFieldValue("THID");"all"==a&&(a="");return"thread.suspend("+a+")\r\n"};Blockly.Lua.thread_sleep=function(a){var b=a.getFieldValue("TIME"),c="";switch(a.getFieldValue("UNITS")){case "microseconds":c+="thread.sleepus("+b+")\r\n";break;case "milliseconds":c+="thread.sleepms("+b+")\r\n";break;case "seconds":c+="thread.sleep("+b+")\r\n"}return c};"use strict";Blockly.Lua["try"]={};
Blockly.Lua.exception_try=function(a){var b=Blockly.Lua.statementToCode(a,"TRY0"),c=Blockly.Lua.statementToCode(a,"CATCH0"),d=Blockly.Lua.statementToCode(a,"FINALLY0"),e;e=""+(Blockly.Lua.indent(0,"try(")+"\n");e+=Blockly.Lua.indent(1,"function()")+"\n";e+=Blockly.Lua.indent(1,b);e+=Blockly.Lua.indent(1,"end, ")+"\n";e+=Blockly.Lua.indent(1,"function(where, line, errCode, msg)")+"\n";""!=c&&(e+=Blockly.Lua.indent(1,c));e+=Blockly.Lua.blockErrorCatched(2,a);""!=d&&(e+=Blockly.Lua.indent(1,"end, ")+
"\n",e+=Blockly.Lua.indent(1,"function()")+"\n",e+=Blockly.Lua.indent(1,d));e+=Blockly.Lua.indent(1,"end")+"\n";return e+=Blockly.Lua.indent(0,")")+"\n"};
Blockly.Lua.exception_catch_error=function(a){var b=Blockly.Lua.statementToCode(a,"DO"),c=a.getFieldValue("ERROR"),d="",d="any"==c?d+(Blockly.Lua.indent(0,"if (errCode ~= nil) then")+"\n"):d+(Blockly.Lua.indent(0,"if ((errCode ~= nil) and (errCode == "+c+")) then")+"\n"),d=d+Blockly.Lua.indent(0,b),d=d+Blockly.Lua.blockErrorCatched(1,a),d=d+(Blockly.Lua.indent(1,"return")+"\n");return d+=Blockly.Lua.indent(0,"end")+"\n"};
Blockly.Lua.exception_raise_again=function(a){return Blockly.Lua.indent(0,'error(errCode..":"..msg)')+"\n"};"use strict";Blockly.Lua.variables={};Blockly.Lua.variables_get=function(a){return"undefined"==typeof Blockly.Lua.variableDB_?["",Blockly.Lua.ORDER_ATOMIC]:[Blockly.Lua.variableDB_.getName(a.getFieldValue("VAR"),Blockly.Variables.NAME_TYPE),Blockly.Lua.ORDER_ATOMIC]};
Blockly.Lua.variables_set=function(a){var b=Blockly.Lua.valueToCode(a,"VALUE",Blockly.Lua.ORDER_NONE)||"0";return"undefined"==typeof Blockly.Lua.variableDB_?["",Blockly.Lua.ORDER_ATOMIC]:Blockly.Lua.variableDB_.getName(a.getFieldValue("VAR"),Blockly.Variables.NAME_TYPE)+" = "+b+"\n"};"use strict";Blockly.Lua.Wifi={};Blockly.Lua.Wifi.helper={};
Blockly.Lua.wifi_start=function(a){var b="",c;c=""+Blockly.Lua.blockStart(0,a);c+=Blockly.Lua.indent(0,"net.wf.setup(net.wf.mode."+a.wtype+', "'+a.ssid+'","'+a.password+'")')+"\n";c+=Blockly.Lua.indent(0,"net.wf.start(false)")+"\n";c+=Blockly.Lua.blockEnd(0,a);b+=Blockly.Lua.indent(0,"-- configure wifi and start wifi")+"\n";return b+=Blockly.Lua.indent(0,Blockly.Lua.tryBlock(0,a,c))+"\n"};
Blockly.Lua.wifi_stop=function(a){var b="",c;c=""+(Blockly.Lua.indent(0,"net.wf.setup(net.wf.mode."+a.wtype+', "'+a.ssid+'","'+a.password+'")')+"\n");c+=Blockly.Lua.indent(0,"net.wf.stop()")+"\n";b+=Blockly.Lua.indent(0,"-- configure wifi and stop wifi")+"\n";return b+=Blockly.Lua.indent(0,Blockly.Lua.tryBlock(0,a,c))+"\n"};
Blockly.Lua.when_wifi_is_conneted=function(a){var b="",c="",d=Blockly.Lua.statementToCodeNoIndent(a,"DO"),c=c+Blockly.Lua.blockStart(0,a);""!=d&&(c+=Blockly.Lua.indent(0,d));c+=Blockly.Lua.blockEnd(0,a);b+=Blockly.Lua.indent(0,"-- when Wi-Fi is connected")+"\n";b+=Blockly.Lua.indent(0,"_network_callback_wifi_connected = function()")+"\n";b+=Blockly.Lua.indent(0,Blockly.Lua.tryBlock(0,a,c))+"\n";b+=Blockly.Lua.indent(0,"end")+"\n";codeSection.declaration.push(b);return""};
Blockly.Lua.when_wifi_is_disconneted=function(a){var b="",c="",d=Blockly.Lua.statementToCodeNoIndent(a,"DO"),c=c+Blockly.Lua.blockStart(0,a);""!=d&&(c+=Blockly.Lua.indent(0,d));c+=Blockly.Lua.blockEnd(0,a);b+=Blockly.Lua.indent(0,"-- when Wi-Fi is disconnected")+"\n";b+=Blockly.Lua.indent(0,"_network_callback_wifi_disconnected = function()")+"\n";b+=Blockly.Lua.indent(0,Blockly.Lua.tryBlock(0,a,c))+"\n";b+=Blockly.Lua.indent(0,"end")+"\n";codeSection.declaration.push(b);return""};
